name: wallet_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  animated_toggle_switch: ^0.8.5
  flutter_switch: ^0.3.2

 # image_picker: ^1.0.7
  image_picker: ^1.1.2
  file_picker: ^10.3.1

  open_filex: ^4.7.0

  # DATABASE
  sqflite: ^2.3.0
  path: ^1.9.0

  # CHARTS
  fl_chart: ^0.68.0

  # EXPORT
  excel: ^2.1.0
  pdf: ^3.11.0
  path_provider: ^2.1.2
  #file_picker: ^8.0.0

  # UTILITIES
  intl: ^0.20.2
  permission_handler: ^11.0.0
  shared_preferences: ^2.2.2

  # NOTIFICATIONS
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.4

  # LOCALIZATION
  flutter_localizations:
    sdk: flutter

  # SMS
  flutter_sms_inbox: ^1.0.4

  # ICONS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/favicon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/NotoSans-Regular.ttf
    #- assets/font/NotoSansTamil-Regular.ttf
    