import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  //////////////////////////////////////////////////
  // SAFE ACCESS
  //////////////////////////////////////////////////
  static AppLocalizations of(BuildContext context) {
    final result = Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    );

    return result ??
        AppLocalizations(const Locale('en'));
  }

  //////////////////////////////////////////////////
  // SUPPORTED LOCALES
  //////////////////////////////////////////////////
  static const List<Locale> supportedLocales = [
    Locale('en'),
    Locale('ta'),
    Locale('hi'),
    Locale('te'),
    Locale('ml'),
    Locale('kn'),
    Locale('bn'),
    Locale('gu'),
    Locale('mr'),
    Locale('pa'),
    Locale('ur'),
    Locale('or'),
  ];

  //////////////////////////////////////////////////
  // TRANSLATIONS
  //////////////////////////////////////////////////
  static const Map<String, Map<String, String>>
      localizedValues = {
    //////////////////////////////////////////////////
    // ENGLISH
    //////////////////////////////////////////////////
    'en': {
      'app_name': 'Wallet Wiz',
      'my_wallet': 'My Wallet',
      'income': 'Income',
      'expense': 'Expense',
      'weekly': 'Weekly',
      'monthly': 'Monthly',
      'yearly': 'Yearly',
      'total': 'Total',
      'recent_transactions':
          'Recent Transactions',
      'view_all': 'View All',
      'home': 'Home',
      'stats': 'Stats',
      'category': 'Category',
      'settings': 'Settings',
      'add': 'Add',
      'balance': 'Balance',
      'currency': 'Currency',
      'select_language':
          'Choose Your Language',
      'language_subtitle':
          'Select your preferred language\nfor the Wallet App',
      'select_currency':
          'Select Currency',
      'currency_subtitle':
          'Choose your preferred currency\nfor transactions and reports.',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'search': 'Search',
      'welcome': 'Welcome',
      'transaction': 'Transaction',
      'transactions': 'Transactions',
      'no_data': 'No Data Found',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'dark_mode': 'Dark Mode',
      'light_mode': 'Light Mode',
      'profile': 'Profile',
      'logout': 'Logout',
      'notification': 'Notification',
      'notifications': 'Notifications',
      'budget': 'Budget',
      'analytics': 'Analytics',
      'reports': 'Reports',
      'expense_tracker': 'Expense Tracker',
      'wallet_balance': 'Wallet Balance',
      'see_all': 'See All',
      'continue': 'Continue',
      'done': 'Done',
      'next': 'Next',
      'skip': 'Skip',
      'quote1': 'Track every rupee. Build every dream.',
      'quote2': 'Spend wisely. Save consistently.',
      'quote3': 'Small savings today, big freedom tomorrow.',
      'quote4': 'A budget is telling your money where to go.',
      'quote5': 'Every expense tells a story.',
      'quote6': 'Control your money before it controls you.',
      'quote7': 'Financial freedom starts with tracking.',
      'quote8': 'Save money today for a better tomorrow.',
      'categories': 'Categories',
      'new_category': 'New Category',
      'add_category': 'Add Category',
      'select_category': 'Select Category',
      'new_subcategory': 'New Subcategory',
      'add_subcategory': 'Add Subcategory',
      'no_categories_yet': 'No categories yet',
      'no_subcategories': 'No subcategories',
      'category_exists': 'Category already exists',
      'subcategory_exists': 'Subcategory already exists',
      'category_added': 'Category added',
      'subcategory_added': 'Subcategory added',
      'food': 'Food',
'breakfast': 'Breakfast',
'lunch': 'Lunch',
'dinner': 'Dinner',
'snacks': 'Snacks',

'travel': 'Travel',
'bus': 'Bus',
'train': 'Train',
'fuel': 'Fuel',
'taxi': 'Taxi',

'shopping': 'Shopping',
'clothes': 'Clothes',
'electronics': 'Electronics',
'groceries': 'Groceries',
'accessories': 'Accessories',

'bills': 'Bills',
'electricity': 'Electricity',
'internet': 'Internet',
'water': 'Water',
'mobile_recharge': 'Mobile Recharge',

'entertainment': 'Entertainment',
'movies': 'Movies',
'games': 'Games',
'music': 'Music',
'ott': 'OTT',

'health': 'Health',
'medicine': 'Medicine',
'doctor': 'Doctor',
'gym': 'Gym',
'insurance': 'Insurance',

'education': 'Education',
'books': 'Books',
'fees': 'Fees',
'courses': 'Courses',
'stationery': 'Stationery',
   "reports_export": "Reports & Export",
  "financial_reports": "Financial Reports",
  "report_subtitle": "Generate professional PDF and Excel reports using selected date ranges.",
  //"select_date_range": "Select Date Range",
  "choose_from_date": "Choose From Date",
  "choose_to_date": "Choose To Date",
  "from": "From",
  "to": "To",
  "download_pdf": "Download PDF Report",
  "download_excel": "Download Excel Report",
  "upload_pdf": "Upload PDF",
  "select_date_range": "Please select date range",
  "no_pdf_selected": "No PDF Selected",
  "pdf_saved": "PDF Saved Successfully",
  "excel_saved": "Excel Saved Successfully",
  "pdf_imported": "PDF Imported",
  "pdf_failed": "Failed to process PDF",
  //"analytics": "Analytics",
//"no_data": "No data",
"financial_overview": "Financial Overview",
"category_expense": "Category Expense",
"daily_expense": "Daily Expenses",
"monthly_expense": "Monthly Expenses",
"smart_wallet": "SMART WALLET",
'add_transaction': 'Add Transaction',
//'save_transaction': 'Save Transaction',
'track_save_grow': 'Track • Save • Grow',
'wallet_login': 'Wallet Login',
'username': 'Username',
'password': 'Password',
'login': 'Login',
'register_prompt': "Don't have an account? Register",
'login_successful': 'Login Successful',
'invalid_credentials': 'Invalid username or password',
'enter_credentials': 'Please enter username and password',
'create_account': 'Create Account',
'fill_all_fields': 'Please fill all fields',
'password_not_match': 'Passwords do not match',
'account_created': 'Account created successfully',
'username_exists': 'Username already exists',
'confirm_password': 'Confirm Password',
'already_have_account': 'Already have an account? Login',
"sub_category_expenses": "Sub Category Expenses",
  //"settings": "Settings",
  "language": "Language",
  //"currency": "Currency",
  "manage_profiles": "Manage Profiles",
  "manage_profiles_desc": "Switch profile, create project, delete project",
  //"reports": "Reports",
  //"categories": "Categories",
  //"dark_mode": "Dark Mode"
  
  "choose_profile": "Choose Profile",
  "choose_workspace": "Choose your workspace",
  "personal": "Personal",
  "manage_personal_expenses": "Manage personal expenses",
  "business": "Business",
  "track_business_finances": "Track business finances",
  "projects": "Projects",
  "no_projects_created": "No Projects Created",
  "create_project": "Create Project",
  "enter_project_name": "Enter Project Name",
  "project_already_exists": "Project already exists",
  //"cancel": "Cancel",
  "create": "Create"




    },

    //////////////////////////////////////////////////
    // TAMIL
    //////////////////////////////////////////////////
    'ta': {
      'app_name': 'வாலெட் விஸ்',
      'my_wallet': 'என் வாலெட்',
      'income': 'வருமானம்',
      'expense': 'செலவு',
      'weekly': 'வாராந்திரம்',
      'monthly': 'மாதாந்திரம்',
      'yearly': 'வருடாந்திரம்',
      'total': 'மொத்தம்',
      'recent_transactions':
          'சமீபத்திய பரிவர்த்தனைகள்',
      'view_all': 'அனைத்தையும் காண்க',
      'home': 'முகப்பு',
      'stats': 'புள்ளிவிவரம்',
      'category': 'வகைகள்',
      'settings': 'அமைப்புகள்',
      'add': 'சேர்',
      'balance': 'இருப்பு',
      'currency': 'நாணயம்',
      'select_language':
          'மொழியை தேர்ந்தெடுக்கவும்',
      'language_subtitle':
          'வாலெட் பயன்பாட்டிற்கான\nஉங்கள் மொழியை தேர்வு செய்யவும்',
      'select_currency':
          'நாணயத்தை தேர்ந்தெடுக்கவும்',
      'currency_subtitle':
          'பரிவர்த்தனைகள் மற்றும் அறிக்கைகளுக்கான\nஉங்கள் நாணயத்தை தேர்வு செய்யவும்.',
      'save': 'சேமிக்கவும்',
      'cancel': 'ரத்து செய்',
      'delete': 'நீக்கு',
      'edit': 'திருத்து',
      'search': 'தேடு',
      'welcome': 'வரவேற்கிறோம்',
      'transaction': 'பரிவர்த்தனை',
      'transactions': 'பரிவர்த்தனைகள்',
      'no_data':
          'தகவல்கள் எதுவும் இல்லை',
      'today': 'இன்று',
      'yesterday': 'நேற்று',
      'dark_mode': 'இருண்ட நிலை',
      'light_mode': 'ஒளி நிலை',
      'profile': 'சுயவிவரம்',
      'logout': 'வெளியேறு',
      'notification': 'அறிவிப்பு',
      'notifications': 'அறிவிப்புகள்',
      'budget': 'பட்ஜெட்',
      'analytics': 'பகுப்பாய்வு',
      'reports': 'அறிக்கைகள்',
      'expense_tracker':
          'செலவு கண்காணிப்பு',
      'wallet_balance':
          'வாலெட் இருப்பு',
      'see_all': 'அனைத்தையும் காண்க',
      'continue': 'தொடரவும்',
      'done': 'முடிந்தது',
      'next': 'அடுத்து',
      'skip': 'தவிர்க்கவும்',
      'quote1': 'ஒவ்வொரு ரூபாயையும் கண்காணிக்கவும். ஒவ்வொரு கனவையும் உருவாக்கவும்.',
      'quote2': 'புத்திசாலித்தனமாக செலவு செய்யுங்கள். தொடர்ந்து சேமிக்கவும்.',
      'quote3': 'இன்றைய சிறிய சேமிப்பு, நாளைய பெரிய சுதந்திரம்.',
      'quote4': 'பட்ஜெட் என்பது உங்கள் பணம் எங்கு செல்ல வேண்டும் என்பதை சொல்லுவது.',
      'quote5': 'ஒவ்வொரு செலவும் ஒரு கதையை சொல்கிறது.',
      'quote6': 'பணம் உங்களை கட்டுப்படுத்துவதற்கு முன் அதை நீங்கள் கட்டுப்படுத்துங்கள்.',
      'quote7': 'நிதி சுதந்திரம் கண்காணிப்பிலிருந்து தொடங்குகிறது.',
      'quote8': 'சிறந்த நாளைக்காக இன்று சேமிக்கவும்.',
        'categories': 'வகைகள்',
        'new_category': 'புதிய வகை',
        'add_category': 'வகையை சேர்',
        'select_category': 'வகையை தேர்ந்தெடு',
        'new_subcategory': 'புதிய துணை வகை',
        'add_subcategory': 'துணை வகையை சேர்',
        'no_categories_yet': 'இன்னும் வகைகள் இல்லை',
        'no_subcategories': 'துணை வகைகள் இல்லை',
        'category_exists': 'வகை ஏற்கனவே உள்ளது',
        'subcategory_exists': 'துணை வகை ஏற்கனவே உள்ளது',
        'category_added': 'வகை சேர்க்கப்பட்டது',
        'subcategory_added': 'துணை வகை சேர்க்கப்பட்டது',
          'food': 'உணவு',
          'breakfast': 'காலை உணவு',
          'lunch': 'மதிய உணவு',
          'dinner': 'இரவு உணவு',
          'snacks': 'சிற்றுண்டி',

          'travel': 'பயணம்',
          'bus': 'பஸ்',
          'train': 'ரயில்',
          'fuel': 'எரிபொருள்',
          'taxi': 'டாக்ஸி',

          'shopping': 'கடைசெய்தல்',
          'clothes': 'உடைகள்',
          'electronics': 'மின்னணு சாதனங்கள்',
          'groceries': 'மளிகை பொருட்கள்',
          'accessories': 'அலங்கார பொருட்கள்',

          'bills': 'பில்கள்',
          'electricity': 'மின்சாரம்',
          'internet': 'இணையம்',
          'water': 'தண்ணீர்',
          'mobile recharge': 'மொபைல் ரீசார்ஜ்',
          'recharge': 'ரீசார்ஜ்',

          'entertainment': 'பொழுதுபோக்கு',
          'movies': 'திரைப்படங்கள்',
          'games': 'விளையாட்டுகள்',
          'music': 'இசை',
          'ott': 'OTT',

          'health': 'ஆரோக்கியம்',
          'medicine': 'மருந்து',
          'doctor': 'மருத்துவர்',
          'gym': 'உடற்பயிற்சி மையம்',
          'insurance': 'காப்பீடு',

          'education': 'கல்வி',
          'books': 'புத்தகங்கள்',
          'fees': 'கட்டணம்',
          'courses': 'பாடநெறிகள்',
          'stationery': 'எழுதுபொருட்கள்',

            "add_transaction": "பரிவர்த்தனை சேர்க்க",
  "enter_amount": "தொகையை உள்ளிடவும்",
 // "income": "வருமானம்",
  //"expense": "செலவு",
  "select_subcategory": "துணை வகையைத் தேர்வு செய்யவும்",
  "save_transaction": "சேமிக்கவும்",
  "reports_export": "அறிக்கைகள் & ஏற்றுமதி",
  "financial_reports": "நிதி அறிக்கைகள்",
  "report_subtitle": "தேதி வரம்பில் PDF மற்றும் Excel அறிக்கைகள் உருவாக்கவும்",
  "select_date_range": "தேதி வரம்பை தேர்வு செய்யவும்",
  "choose_from_date": "தொடக்க தேதியை தேர்வு செய்யவும்",
  "choose_to_date": "முடிவு தேதியை தேர்வு செய்யவும்",
  "from": "இருந்து",
  "to": "வரை",
  "download_pdf": "PDF பதிவிறக்கு",
  "download_excel": "Excel பதிவிறக்கு",
  "upload_pdf": "PDF பதிவேற்று",
  //"analytics": "பகுப்பாய்வு",
//  "no_data": "தரவு இல்லை",
"financial_overview": "நிதி சுருக்கம்",
"category_expense": "வகை செலவு",
"daily_expense": "தினசரி செலவுகள்",
"monthly_expense": "மாதாந்திர செலவுகள்",
"salary": "சம்பளம்",
"others": "மற்றவை",
"smart_wallet": "ஸ்மார்ட் வாலெட்",
'add transaction':'பரிவர்த்தனையைச் சேர்க்கவும்',
//'save_transaction': 'பரிவர்த்தனையை சேமிக்கவும்',
'track_save_grow': 'கண்காணி • சேமி • வளர்ச்சி',

'wallet_login': 'வாலெட் உள்நுழைவு',
'username': 'பயனர் பெயர்',
'password': 'கடவுச்சொல்',
'login': 'உள்நுழை',
'register_prompt': 'கணக்கு இல்லையா? பதிவு செய்யவும்',
'login_successful': 'உள்நுழைவு வெற்றி',
'invalid_credentials': 'தவறான பயனர் பெயர் அல்லது கடவுச்சொல்',
'enter_credentials': 'பயனர் பெயர் மற்றும் கடவுச்சொல்லை உள்ளிடவும்',

'create_account': 'கணக்கு உருவாக்கவும்',
'fill_all_fields': 'அனைத்து புலங்களையும் நிரப்பவும்',
'password_not_match': 'கடவுச்சொற்கள் பொருந்தவில்லை',
'account_created': 'கணக்கு வெற்றிகரமாக உருவாக்கப்பட்டது',
'username_exists': 'பயனர் பெயர் ஏற்கனவே உள்ளது',
'confirm_password': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
'already_have_account': 'ஏற்கனவே கணக்கு உள்ளதா? உள்நுழையவும்',
"sub_category_expenses": "துணைப்பிரிவு செலவுகள்",
"language": "மொழி",
"manage_profiles": "சுயவிவரங்களை நிர்வகி",
"manage_profiles_desc": "சுயவிவரத்தை மாற்றவும், திட்டத்தை உருவாக்கவும், திட்டத்தை நீக்கவும்",
"choose_profile": "சுயவிவரத்தை தேர்ந்தெடுக்கவும்",
  "choose_workspace": "உங்கள் பணியிடத்தை தேர்ந்தெடுக்கவும்",
  "personal": "தனிப்பட்டது",
  "manage_personal_expenses": "தனிப்பட்ட செலவுகளை நிர்வகிக்கவும்",
  "business": "வணிகம்",
  "track_business_finances": "வணிக நிதிகளை கண்காணிக்கவும்",
  "projects": "திட்டங்கள்",
  "no_projects_created": "திட்டங்கள் எதுவும் உருவாக்கப்படவில்லை",
  "create_project": "திட்டம் உருவாக்கு",
  "enter_project_name": "திட்டத்தின் பெயரை உள்ளிடவும்",
  "project_already_exists": "திட்டம் ஏற்கனவே உள்ளது",
  //"cancel": "ரத்து செய்",
  "create": "உருவாக்கு"
    },

    //////////////////////////////////////////////////
    // HINDI
    //////////////////////////////////////////////////
    'hi': {
      'app_name': 'वॉलेट विज़',
      'my_wallet': 'मेरा वॉलेट',
      'income': 'आय',
      'expense': 'खर्च',
      'weekly': 'साप्ताहिक',
      'monthly': 'मासिक',
      'yearly': 'वार्षिक',
      'total': 'कुल',
      'recent_transactions':
          'हाल की लेनदेन',
      'view_all': 'सभी देखें',
      'home': 'होम',
      'stats': 'आंकड़े',
      'category': 'श्रेणी',
      'settings': 'सेटिंग्स',
      'add': 'जोड़ें',
      'balance': 'बैलेंस',
      'currency': 'मुद्रा',
      'select_language':
          'भाषा चुनें',
      'language_subtitle':
          'वॉलेट ऐप के लिए\nअपनी भाषा चुनें',
      'select_currency':
          'मुद्रा चुनें',
      'currency_subtitle':
          'लेनदेन और रिपोर्ट के लिए\nअपनी पसंदीदा मुद्रा चुनें।',
      'save': 'सहेजें',
      'cancel': 'रद्द करें',
      'delete': 'हटाएं',
      'edit': 'संपादित करें',
      'search': 'खोजें',
      'welcome': 'स्वागत है',
      'transaction': 'लेनदेन',
      'transactions': 'लेनदेन',
      'no_data':
          'कोई डेटा नहीं मिला',
      'today': 'आज',
      'yesterday': 'कल',
      'dark_mode': 'डार्क मोड',
      'light_mode': 'लाइट मोड',
      'profile': 'प्रोफाइल',
      'logout': 'लॉगआउट',
      'notification': 'सूचना',
      'notifications': 'सूचनाएं',
      'budget': 'बजट',
      'analytics': 'विश्लेषण',
      'reports': 'रिपोर्ट',
      'expense_tracker':
          'खर्च ट्रैकर',
      'wallet_balance':
          'वॉलेट बैलेंस',
      'see_all': 'सभी देखें',
      'continue': 'जारी रखें',
      'done': 'पूर्ण',
      'next': 'अगला',
      'skip': 'छोड़ें',
      'quote1': 'हर रुपये को ट्रैक करें। हर सपने को बनाएं।',
      'quote2': 'समझदारी से खर्च करें। लगातार बचत करें।',
      'quote3': 'आज की छोटी बचत, कल की बड़ी आज़ादी।',
      'quote4': 'बजट आपके पैसे को दिशा देता है।',
      'quote5': 'हर खर्च एक कहानी बताता है।',
      'quote6': 'पैसे को नियंत्रित करें, इससे पहले कि वह आपको नियंत्रित करे।',
      'quote7': 'वित्तीय स्वतंत्रता ट्रैकिंग से शुरू होती है।',
      'quote8': 'बेहतर कल के लिए आज बचत करें।',
        'categories': 'श्रेणियाँ',
        'new_category': 'नई श्रेणी',
        'add_category': 'श्रेणी जोड़ें',
        'select_category': 'श्रेणी चुनें',
        'new_subcategory': 'नई उपश्रेणी',
        'add_subcategory': 'उपश्रेणी जोड़ें',
        'no_categories_yet': 'अभी तक कोई श्रेणियाँ नहीं',
        'no_subcategories': 'कोई उपश्रेणी नहीं',
        'category_exists': 'श्रेणी पहले से मौजूद है',
        'subcategory_exists': 'उपश्रेणी पहले से मौजूद है',
        'category_added': 'श्रेणी जोड़ दी गई',
        'subcategory_added': 'उपश्रेणी जोड़ दी गई',
        'food': 'भोजन',
        'breakfast': 'नाश्ता',
        'lunch': 'दोपहर का भोजन',
        'dinner': 'रात का खाना',
        'snacks': 'स्नैक्स',

        'travel': 'यात्रा',
        'bus': 'बस',
        'train': 'ट्रेन',
        'fuel': 'ईंधन',
        'taxi': 'टैक्सी',

        'shopping': 'खरीदारी',
        'clothes': 'कपड़े',
        'electronics': 'इलेक्ट्रॉनिक्स',
        'groceries': 'किराना',
        'accessories': 'सामान',

        'bills': 'बिल',
        'electricity': 'बिजली',
        'internet': 'इंटरनेट',
        'water': 'पानी',
        'mobile_recharge': 'मोबाइल रिचार्ज',

        'entertainment': 'मनोरंजन',
        'movies': 'फिल्में',
        'games': 'गेम्स',
        'music': 'संगीत',
        'ott': 'OTT',

        'health': 'स्वास्थ्य',
        'medicine': 'दवा',
        'doctor': 'डॉक्टर',
        'gym': 'जिम',
        'insurance': 'बीमा',

        'education': 'शिक्षा',
        'books': 'किताबें',
        'fees': 'फीस',
        'courses': 'कोर्स',
        'stationery': 'स्टेशनरी',
        "add_transaction": "लेन-देन जोड़ें",
  "enter_amount": "राशि दर्ज करें",
  //"income": "आय",
  //"expense": "खर्च",
  "select_subcategory": "उप-श्रेणी चुनें",
  "save_transaction": "सहेजें",
  "reports_export": "रिपोर्ट और निर्यात",
  "financial_reports": "वित्तीय रिपोर्ट",
  "report_subtitle": "तारीख सीमा के अनुसार PDF और Excel रिपोर्ट बनाएं",
  "select_date_range": "तारीख सीमा चुनें",
  "choose_from_date": "शुरुआती तारीख चुनें",
  "choose_to_date": "अंतिम तारीख चुनें",
  "from": "से",
  "to": "तक",
  "download_pdf": "PDF डाउनलोड करें",
  "download_excel": "Excel डाउनलोड करें",
  "upload_pdf": "PDF अपलोड करें",
   // "analytics": "विश्लेषण",
//"no_data": "कोई डेटा नहीं",
"financial_overview": "वित्तीय अवलोकन",
"category_expense": "श्रेणी खर्च",
"daily_expense": "दैनिक खर्च",
"monthly_expense": "मासिक खर्च",
"salary": "वेतन",
"others": "अन्य",
"smart_wallet": "स्मार्ट वॉलेट",
//'add_transaction': 'लेन-देन जोड़ें',
//'save_transaction': 'लेन-देन सहेजें',
'track_save_grow': 'ट्रैक करें • बचत करें • बढ़ें',
'wallet_login': 'वॉलेट लॉगिन',
'username': 'उपयोगकर्ता नाम',
'password': 'पासवर्ड',
'login': 'लॉगिन',
'register_prompt': 'खाता नहीं है? पंजीकरण करें',
'login_successful': 'लॉगिन सफल',
'invalid_credentials': 'गलत उपयोगकर्ता नाम या पासवर्ड',
'enter_credentials': 'कृपया उपयोगकर्ता नाम और पासवर्ड दर्ज करें',
'create_account': 'खाता बनाएं',
'fill_all_fields': 'कृपया सभी फ़ील्ड भरें',
'password_not_match': 'पासवर्ड मेल नहीं खाते',
'account_created': 'खाता सफलतापूर्वक बनाया गया',
'username_exists': 'उपयोगकर्ता नाम पहले से मौजूद है',
'confirm_password': 'पासवर्ड की पुष्टि करें',
'already_have_account': 'पहले से खाता है? लॉगिन करें',
"sub_category_expenses": "उप-श्रेणी खर्च",
"language": "भाषा",
"manage_profiles": "प्रोफाइल प्रबंधन",
"manage_profiles_desc": "प्रोफ़ाइल बदलें, प्रोजेक्ट बनाएं, प्रोजेक्ट हटाएं",

  "choose_profile": "प्रोफ़ाइल चुनें",
  "choose_workspace": "अपना कार्यक्षेत्र चुनें",
  "personal": "व्यक्तिगत",
  "manage_personal_expenses": "व्यक्तिगत खर्चों का प्रबंधन करें",
  "business": "व्यवसाय",
  "track_business_finances": "व्यावसायिक वित्त का ट्रैक रखें",
  "projects": "परियोजनाएँ",
  "no_projects_created": "कोई परियोजना नहीं बनाई गई",
  "create_project": "परियोजना बनाएँ",
  "enter_project_name": "परियोजना का नाम दर्ज करें",
  "project_already_exists": "परियोजना पहले से मौजूद है",
  //"cancel": "रद्द करें",
  "create": "बनाएँ"
  },
  
          //////////////////////////////////////////////////
          // TELUGU
          //////////////////////////////////////////////////

          'te': {
            'app_name': 'వాలెట్ విజ్',
            'my_wallet': 'నా వాలెట్',
            'income': 'ఆదాయం',
            'expense': 'ఖర్చు',
            'weekly': 'వారానికి',
            'monthly': 'నెలవారీ',
            'yearly': 'వార్షిక',
            'total': 'మొత్తం',
            'recent_transactions': 'ఇటీవలి లావాదేవీలు',
            'view_all': 'అన్నీ చూడండి',
            'home': 'హోమ్',
            'stats': 'గణాంకాలు',
            'category': 'వర్గం',
            'settings': 'సెట్టింగ్స్',
            'add': 'జోడించు',
            'balance': 'బ్యాలెన్స్',
            'currency': 'కరెన్సీ',
            'select_language': 'భాషను ఎంచుకోండి',
            'language_subtitle':
                'వాలెట్ యాప్ కోసం\nమీ భాషను ఎంచుకోండి',
            'select_currency': 'కరెన్సీ ఎంచుకోండి',
            'currency_subtitle':
                'లావాదేవీలు మరియు నివేదికల కోసం\nమీ కరెన్సీని ఎంచుకోండి.',
            'save': 'సేవ్',
            'cancel': 'రద్దు',
            'delete': 'తొలగించు',
            'edit': 'సవరించు',
            'search': 'వెతుకు',
            'welcome': 'స్వాగతం',
            'transaction': 'లావాదేవీ',
            'transactions': 'లావాదేవీలు',
            'no_data': 'డేటా లేదు',
            'today': 'ఈ రోజు',
            'yesterday': 'నిన్న',
            'dark_mode': 'డార్క్ మోడ్',
            'light_mode': 'లైట్ మోడ్',
            'profile': 'ప్రొఫైల్',
            'logout': 'లాగౌట్',
            'notification': 'నోటిఫికేషన్',
            'notifications': 'నోటిఫికేషన్లు',
            'budget': 'బడ్జెట్',
            'analytics': 'విశ్లేషణ',
            'reports': 'రిపోర్ట్స్',
            'expense_tracker': 'ఖర్చు ట్రాకర్',
            'wallet_balance': 'వాలెట్ బ్యాలెన్స్',
            'see_all': 'అన్నీ చూడండి',
            'continue': 'కొనసాగించు',
            'done': 'పూర్తైంది',
            'next': 'తర్వాత',
            'skip': 'దాటవేయి',
            'quote1': 'ప్రతి రూపాయిని ట్రాక్ చేయండి. ప్రతి కలను నిర్మించండి.',
            'quote2': 'తెలివిగా ఖర్చు చేయండి. నిరంతరం పొదుపు చేయండి.',
            'quote3': 'ఈరోజు చిన్న పొదుపు, రేపటి పెద్ద స్వేచ్ఛ.',
            'quote4': 'బడ్జెట్ అంటే మీ డబ్బు ఎక్కడికి వెళ్లాలో చెప్పడం.',
            'quote5': 'ప్రతి ఖర్చు ఒక కథ చెబుతుంది.',
            'quote6': 'డబ్బు మిమ్మల్ని నియంత్రించే ముందు మీరు దాన్ని నియంత్రించండి.',
            'quote7': 'ఆర్థిక స్వేచ్ఛ ట్రాకింగ్‌తో ప్రారంభమవుతుంది.',
            'quote8': 'మంచి రేపటికి ఈరోజే పొదుపు చేయండి.',
            'categories': 'వర్గాలు',
            'new_category': 'కొత్త వర్గం',
            'add_category': 'వర్గాన్ని జోడించండి',
            'select_category': 'వర్గాన్ని ఎంచుకోండి',
            'new_subcategory': 'కొత్త ఉపవర్గం',
            'add_subcategory': 'ఉపవర్గాన్ని జోడించండి',
            'no_categories_yet': 'ఇంకా వర్గాలు లేవు',
            'no_subcategories': 'ఉపవర్గాలు లేవు',
            'category_exists': 'వర్గం ఇప్పటికే ఉంది',
            'subcategory_exists': 'ఉపవర్గం ఇప్పటికే ఉంది',
            'category_added': 'వర్గం జోడించబడింది',
            'subcategory_added': 'ఉపవర్గం జోడించబడింది',
            
            'food': 'ఆహారం',
            'breakfast': 'ఉదయం అల్పాహారం',
            'lunch': 'మధ్యాహ్న భోజనం',
            'dinner': 'రాత్రి భోజనం',
            'snacks': 'తినుబండారాలు',

            'travel': 'ప్రయాణం',
            'bus': 'బస్సు',
            'train': 'రైలు',
            'fuel': 'ఇంధనం',
            'taxi': 'టాక్సీ',

            'shopping': 'షాపింగ్',
            'clothes': 'బట్టలు',
            'electronics': 'ఎలక్ట్రానిక్స్',
            'groceries': 'కిరాణా',
            'accessories': 'ఉపకరణాలు',

            'bills': 'బిల్లులు',
            'electricity': 'విద్యుత్',
            'internet': 'ఇంటర్నెట్',
            'water': 'నీరు',
            'mobile_recharge': 'మొబైల్ రీచార్జ్',

            'entertainment': 'వినోదం',
            'movies': 'సినిమాలు',
            'games': 'ఆటలు',
            'music': 'సంగీతం',
            'ott': 'OTT',

            'health': 'ఆరోగ్యం',
            'medicine': 'ఔషధం',
            'doctor': 'డాక్టర్',
            'gym': 'జిమ్',
            'insurance': 'భీమా',

            'education': 'విద్య',
            'books': 'పుస్తకాలు',
            'fees': 'ఫీజులు',
            'courses': 'కోర్సులు',
            'stationery': 'స్టేషనరీ',

  "add_transaction": "లావాదేవీ జోడించండి",
  "enter_amount": "మొత్తం నమోదు చేయండి",
 // "income": "ఆదాయం",
  //"expense": "ఖర్చు",
  "select_subcategory": "ఉపవర్గం ఎంచుకోండి",
  "save_transaction": "సేవ్ చేయండి",
  "reports_export": "నివేదికలు & ఎగుమతి",
  "financial_reports": "ఆర్థిక నివేదికలు",
  "report_subtitle": "తేదీ పరిధి ఆధారంగా PDF మరియు Excel నివేదికలు రూపొందించండి",
  "select_date_range": "తేదీ పరిధి ఎంచుకోండి",
  "choose_from_date": "ప్రారంభ తేదీ ఎంచుకోండి",
  "choose_to_date": "ముగింపు తేదీ ఎంచుకోండి",
  "from": "నుండి",
  "to": "వరకు",
  "download_pdf": "PDF డౌన్‌లోడ్",
  "download_excel": "Excel డౌన్‌లోడ్",
  "upload_pdf": "PDF అప్‌లోడ్",

   // "analytics": "విశ్లేషణ",
//"no_data": "డేటా లేదు",
"financial_overview": "ఆర్థిక అవలోకనం",
"category_expense": "వర్గ ఖర్చు",
"daily_expense": "రోజువారీ ఖర్చులు",
"monthly_expense": "మాసిక ఖర్చులు",
"smart_wallet": "స్మార్ట్ వాలెట్",
//'add_transaction': 'లావాదేవీని జోడించండి',
//'save_transaction': 'లావాదేవీని సేవ్ చేయండి',
'track_save_grow': 'ట్రాక్ చేయండి • పొదుపు చేయండి • అభివృద్ధి చెందండి',
'wallet_login': 'వాలెట్ లాగిన్',
'username': 'వినియోగదారు పేరు',
'password': 'పాస్‌వర్డ్',
'login': 'లాగిన్',
'register_prompt': 'ఖాతా లేదా? నమోదు చేసుకోండి',
'login_successful': 'లాగిన్ విజయవంతం',
'invalid_credentials': 'తప్పు వినియోగదారు పేరు లేదా పాస్‌వర్డ్',
'enter_credentials': 'దయచేసి వినియోగదారు పేరు మరియు పాస్‌వర్డ్ నమోదు చేయండి',
'create_account': 'ఖాతా సృష్టించండి',
'fill_all_fields': 'దయచేసి అన్ని వివరాలను నమోదు చేయండి',
'password_not_match': 'పాస్‌వర్డ్లు సరిపోలలేదు',
'account_created': 'ఖాతా విజయవంతంగా సృష్టించబడింది',
'username_exists': 'వినియోగదారు పేరు ఇప్పటికే ఉంది',
'confirm_password': 'పాస్‌వర్డ్‌ను నిర్ధారించండి',
'already_have_account': 'ఇప్పటికే ఖాతా ఉందా? లాగిన్ చేయండి',
"sub_category_expenses": "ఉప వర్గ ఖర్చులు",
"language": "భాష",
"manage_profiles": "ప్రొఫైల్‌లను నిర్వహించండి",
"manage_profiles_desc": "ప్రొఫైల్ మార్చండి, ప్రాజెక్ట్ సృష్టించండి, ప్రాజెక్ట్ తొలగించండి",
"choose_profile": "ప్రొఫైల్‌ను ఎంచుకోండి",
  "choose_workspace": "మీ వర్క్‌స్పేస్‌ను ఎంచుకోండి",
  "personal": "వ్యక్తిగత",
  "manage_personal_expenses": "వ్యక్తిగత ఖర్చులను నిర్వహించండి",
  "business": "వ్యాపారం",
  "track_business_finances": "వ్యాపార ఆర్థికాలను ట్రాక్ చేయండి",
  "projects": "ప్రాజెక్టులు",
  "no_projects_created": "ప్రాజెక్టులు సృష్టించబడలేదు",
  "create_project": "ప్రాజెక్ట్ సృష్టించండి",
  "enter_project_name": "ప్రాజెక్ట్ పేరు నమోదు చేయండి",
  "project_already_exists": "ప్రాజెక్ట్ ఇప్పటికే ఉంది",
  //"cancel": "రద్దు",
  "create": "సృష్టించు"

          },

          //////////////////////////////////////////////////
          // MALAYALAM
          //////////////////////////////////////////////////

          'ml': {
            'app_name': 'വാലറ്റ് വിസ்',
            'my_wallet': 'എന്റെ വാലറ്റ്',
            'income': 'വരുമാനം',
            'expense': 'ചെലവ്',
            'weekly': 'ആഴ്ചതോറും',
            'monthly': 'മാസത്തിൽ',
            'yearly': 'വാർഷികം',
            'total': 'ആകെ',
            'recent_transactions': 'സമീപകാല ഇടപാടുകൾ',
            'view_all': 'എല്ലാം കാണുക',
            'home': 'ഹോം',
            'stats': 'സ്ഥിതിവിവരക്കണക്കുകൾ',
            'category': 'വിഭാഗം',
            'settings': 'ക്രമീകരണങ്ങൾ',
            'add': 'ചേർക്കുക',
            'balance': 'ബാലൻസ്',
            'currency': 'കറൻസി',
            'select_language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
            'language_subtitle':
                'വാലറ്റ് ആപ്പിനായി\nനിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക',
            'select_currency': 'കറൻസി തിരഞ്ഞെടുക്കുക',
            'currency_subtitle':
                'ഇടപാടുകൾക്കും റിപ്പോർട്ടുകൾക്കുമായി\nനിങ്ങളുടെ കറൻസി തിരഞ്ഞെടുക്കുക.',
            'save': 'സേവ്',
            'cancel': 'റദ്ദാക്കുക',
            'delete': 'ഇല്ലാതാക്കുക',
            'edit': 'തിരുത്തുക',
            'search': 'തിരയുക',
            'welcome': 'സ്വാഗതം',
            'transaction': 'ഇടപാട്',
            'transactions': 'ഇടപാടുകൾ',
            'no_data': 'ഡാറ്റ കണ്ടെത്തിയില്ല',
            'today': 'ഇന്ന്',
            'yesterday': 'ഇന്നലെ',
            'dark_mode': 'ഡാർക്ക് മോഡ്',
            'light_mode': 'ലൈറ്റ് മോഡ്',
            'profile': 'പ്രൊഫൈൽ',
            'logout': 'ലോഗ്ഔട്ട്',
            'notification': 'അറിയിപ്പ്',
            'notifications': 'അറിയിപ്പുകൾ',
            'budget': 'ബജറ്റ്',
            'analytics': 'വിശകലനം',
            'reports': 'റിപ്പോർട്ടുകൾ',
            'expense_tracker': 'ചെലവ് ട്രാക്കർ',
            'wallet_balance': 'വാലറ്റ് ബാലൻസ്',
            'see_all': 'എല്ലാം കാണുക',
            'continue': 'തുടരുക',
            'done': 'പൂർത്തിയായി',
            'next': 'അടുത്തത്',
            'skip': 'ഒഴിവാക്കുക',
            'quote1': 'ഓരോ രൂപയും ട്രാക്ക് ചെയ്യൂ. ഓരോ സ്വപ്നവും നിർമ്മിക്കൂ.',
            'quote2': 'ബുദ്ധിപൂർവ്വം ചെലവഴിക്കൂ. സ്ഥിരമായി സംരക്ഷിക്കൂ.',
            'quote3': 'ഇന്നത്തെ ചെറിയ സമ്പാദ്യം, നാളെയുടെ വലിയ സ്വാതന്ത്ര്യം.',
            'quote4': 'ബഡ്ജറ്റ് എന്നത് നിങ്ങളുടെ പണം എവിടെ പോകണമെന്ന് പറയുന്നതാണ്.',
            'quote5': 'ഓരോ ചെലവും ഒരു കഥ പറയുന്നു.',
            'quote6': 'പണം നിങ്ങളെ നിയന്ത്രിക്കുന്നതിന് മുമ്പ് നിങ്ങൾ അത് നിയന്ത്രിക്കൂ.',
            'quote7': 'സാമ്പത്തിക സ്വാതന്ത്ര്യം ട്രാക്കിംഗിൽ നിന്ന് ആരംഭിക്കുന്നു.',
            'quote8': 'നല്ല നാളേക്കായി ഇന്ന് പണം സംരക്ഷിക്കൂ.',
            'categories': 'വിഭാഗങ്ങൾ',
            'new_category': 'പുതിയ വിഭാഗം',
            'add_category': 'വിഭാഗം ചേർക്കുക',
            'select_category': 'വിഭാഗം തിരഞ്ഞെടുക്കുക',
            'new_subcategory': 'പുതിയ ഉപവിഭാഗം',
            'add_subcategory': 'ഉപവിഭാഗം ചേർക്കുക',
            'no_categories_yet': 'ഇതുവരെ വിഭാഗങ്ങളില്ല',
            'no_subcategories': 'ഉപവിഭാഗങ്ങളില്ല',
            'category_exists': 'വിഭാഗം ഇതിനകം നിലവിലുണ്ട്',
            'subcategory_exists': 'ഉപവിഭാഗം ഇതിനകം നിലവിലുണ്ട്',
            'category_added': 'വിഭാഗം ചേർത്തു',
            'subcategory_added': 'ഉപവിഭാഗം ചേർത്തു',
            'food': 'ഭക്ഷണം',
            'breakfast': 'പ്രഭാതഭക്ഷണം',
            'lunch': 'ഉച്ചഭക്ഷണം',
            'dinner': 'വൈകുന്നേരഭക്ഷണം',
            'snacks': 'ലഘുഭക്ഷണം',

            'travel': 'യാത്ര',
            'bus': 'ബസ്',
            'train': 'ട്രെയിൻ',
            'fuel': 'ഇന്ധനം',
            'taxi': 'ടാക്സി',

            'shopping': 'ഷോപ്പിംഗ്',
            'clothes': 'വസ്ത്രങ്ങൾ',
            'electronics': 'ഇലക്ട്രോണിക്സ്',
            'groceries': 'മളിക സാധനങ്ങൾ',
            'accessories': 'ആക്സസറികൾ',

            'bills': 'ബില്ലുകൾ',
            'electricity': 'വൈദ്യുതി',
            'internet': 'ഇന്റർനെറ്റ്',
            'water': 'വെള്ളം',
            'mobile_recharge': 'മൊബൈൽ റീചാർജ്',

            'entertainment': 'വിനോദം',
            'movies': 'സിനിമകൾ',
            'games': 'കളികൾ',
            'music': 'സംഗീതം',
            'ott': 'OTT',

            'health': 'ആരോഗ്യം',
            'medicine': 'മരുന്ന്',
            'doctor': 'ഡോക്ടർ',
            'gym': 'ജിം',
            'insurance': 'ഇൻഷുറൻസ്',

            'education': 'വിദ്യാഭ്യാസം',
            'books': 'പുസ്തകങ്ങൾ',
            'fees': 'ഫീസ്',
            'courses': 'കോഴ്സുകൾ',
            'stationery': 'സ്റ്റേഷനറി',
            "add_transaction": "ഇടപാട് ചേർക്കുക",
  "enter_amount": "തുക നൽകുക",
 // "income": "വരുമാനം",
  //"expense": "ചെലവ്",
  "select_subcategory": "ഉപവിഭാഗം തിരഞ്ഞെടുക്കുക",
  "save_transaction": "സംരക്ഷിക്കുക",
  "reports_export": "റിപ്പോർട്ടുകൾ & എക്സ്പോർട്ട്",
  "financial_reports": "ധനകാര്യ റിപ്പോർട്ടുകൾ",
  "report_subtitle": "തീയതി പരിധിയിൽ PDF, Excel റിപ്പോർട്ടുകൾ സൃഷ്ടിക്കുക",
  "select_date_range": "തീയതി പരിധി തിരഞ്ഞെടുക്കുക",
  "choose_from_date": "ആരംഭ തീയതി തിരഞ്ഞെടുക്കുക",
  "choose_to_date": "അവസാന തീയതി തിരഞ്ഞെടുക്കുക",
  "from": "മുതൽ",
  "to": "വരെ",
  "download_pdf": "PDF ഡൗൺലോഡ്",
  "download_excel": "Excel ഡൗൺലോഡ്",
  "upload_pdf": "PDF അപ്‌ലോഡ്",

    //"analytics": "വിശകലനം",
//"no_data": "ഡാറ്റ ഇല്ല",
"financial_overview": "ധനകാര്യ അവലോകനം",
"category_expense": "വിഭാഗ ചെലവ്",

"daily_expense": "ദൈനംദിന ചെലവുകൾ",
"monthly_expense": "മാസാന്ത്യ ചെലവുകൾ",
"salary": "ശമ്പളം",
"others": "മറ്റുള്ളവ",
"smart_wallet": "സ്മാർട്ട് വാലറ്റ്",
//'add_transaction': 'ഇടപാട് ചേർക്കുക',
//'save_transaction': 'ഇടപാട് സേവ് ചെയ്യുക',
'track_save_grow': 'നിരീക്ഷിക്കുക • സംരക്ഷിക്കുക • വളരുക',
'wallet_login': 'വാലറ്റ് ലോഗിൻ',
'username': 'ഉപയോക്തൃനാമം',
'password': 'പാസ്‌വേഡ്',
'login': 'ലോഗിൻ',
'register_prompt': 'അക്കൗണ്ട് ഇല്ലേ? രജിസ്റ്റർ ചെയ്യുക',
'login_successful': 'ലോഗിൻ വിജയകരം',
'invalid_credentials': 'തെറ്റായ ഉപയോക്തൃനാമം അല്ലെങ്കിൽ പാസ്‌വേഡ്',
'enter_credentials': 'ദയവായി ഉപയോക്തൃനാമവും പാസ്‌വേഡും നൽകുക',

'create_account': 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
'fill_all_fields': 'ദയവായി എല്ലാ ഫീൽഡുകളും പൂരിപ്പിക്കുക',
'password_not_match': 'പാസ്‌വേഡുകൾ പൊരുത്തപ്പെടുന്നില്ല',
'account_created': 'അക്കൗണ്ട് വിജയകരമായി സൃഷ്ടിച്ചു',
'username_exists': 'ഉപയോക്തൃനാമം ഇതിനകം നിലവിലുണ്ട്',
'confirm_password': 'പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
'already_have_account': 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ? ലോഗിൻ ചെയ്യുക',
"language": "ഭാഷ",
"manage_profiles": "പ്രൊഫൈലുകൾ നിയന്ത്രിക്കുക",
"manage_profiles_desc": "പ്രൊഫൈൽ മാറ്റുക, പ്രോജക്റ്റ് സൃഷ്ടിക്കുക, പ്രോജക്റ്റ് ഇല്ലാതാക്കുക",
"sub_category_expenses": "ഉപവിഭാഗ ചെലവുകൾ",
"choose_profile": "പ്രൊഫൈൽ തിരഞ്ഞെടുക്കുക",
  "choose_workspace": "നിങ്ങളുടെ വർക്ക്‌സ്‌പേസ് തിരഞ്ഞെടുക്കുക",
  "personal": "വ്യക്തിഗതം",
  "manage_personal_expenses": "വ്യക്തിഗത ചെലവുകൾ നിയന്ത്രിക്കുക",
  "business": "ബിസിനസ്",
  "track_business_finances": "ബിസിനസ് സാമ്പത്തികം നിരീക്ഷിക്കുക",
  "projects": "പ്രോജക്റ്റുകൾ",
  "no_projects_created": "പ്രോജക്റ്റുകളൊന്നും സൃഷ്ടിച്ചിട്ടില്ല",
  "create_project": "പ്രോജക്റ്റ് സൃഷ്ടിക്കുക",
  "enter_project_name": "പ്രോജക്റ്റിന്റെ പേര് നൽകുക",
  "project_already_exists": "പ്രോജക്റ്റ് ഇതിനകം നിലവിലുണ്ട്",
  //"cancel": "റദ്ദാക്കുക",
  "create": "സൃഷ്ടിക്കുക"
          },

          //////////////////////////////////////////////////
          // KANNADA
          //////////////////////////////////////////////////

          'kn': {
            'app_name': 'ವಾಲೆಟ್ ವಿಜ್',
            'my_wallet': 'ನನ್ನ ವಾಲೆಟ್',
            'income': 'ಆದಾಯ',
            'expense': 'ಖರ್ಚು',
            'weekly': 'ವಾರದ',
            'monthly': 'ತಿಂಗಳ',
            'yearly': 'ವಾರ್ಷಿಕ',
            'total': 'ಒಟ್ಟು',
            'recent_transactions': 'ಇತ್ತೀಚಿನ ವ್ಯವಹಾರಗಳು',
            'view_all': 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
            'home': 'ಮುಖಪುಟ',
            'stats': 'ಅಂಕಿಅಂಶಗಳು',
            'category': 'ವರ್ಗ',
            'settings': 'ಸೆಟ್ಟಿಂಗ್ಗಳು',
            'add': 'ಸೇರಿಸಿ',
            'balance': 'ಬ್ಯಾಲೆನ್ಸ್',
            'currency': 'ಕರೆನ್ಸಿ',
            'select_language': 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
            'language_subtitle':
                'ವಾಲೆಟ್ ಆಪ್‌ಗಾಗಿ\nನಿಮ್ಮ ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
            'select_currency': 'ಕರೆನ್ಸಿ ಆಯ್ಕೆಮಾಡಿ',
            'currency_subtitle':
                'ವಹಿವಾಟುಗಳು ಮತ್ತು ವರದಿಗಳಿಗಾಗಿ\nನಿಮ್ಮ ಕರೆನ್ಸಿ ಆಯ್ಕೆಮಾಡಿ.',
            'save': 'ಉಳಿಸಿ',
            'cancel': 'ರದ್ದುಮಾಡಿ',
            'delete': 'ಅಳಿಸಿ',
            'edit': 'ತಿದ್ದು',
            'search': 'ಹುಡುಕಿ',
            'welcome': 'ಸ್ವಾಗತ',
            'transaction': 'ವಹಿವಾಟು',
            'transactions': 'ವಹಿವಾಟುಗಳು',
            'no_data': 'ಡೇಟಾ ಸಿಗಲಿಲ್ಲ',
            'today': 'ಇಂದು',
            'yesterday': 'ನಿನ್ನೆ',
            'dark_mode': 'ಡಾರ್ಕ್ ಮೋಡ್',
            'light_mode': 'ಲೈಟ್ ಮೋಡ್',
            'profile': 'ಪ್ರೊಫೈಲ್',
            'logout': 'ಲಾಗ್ ಔಟ್',
            'notification': 'ಅಧಿಸೂಚನೆ',
            'notifications': 'ಅಧಿಸೂಚನೆಗಳು',
            'budget': 'ಬಜೆಟ್',
            'analytics': 'ವಿಶ್ಲೇಷಣೆ',
            'reports': 'ವರದಿಗಳು',
            'expense_tracker': 'ಖರ್ಚು ಟ್ರ್ಯಾಕರ್',
            'wallet_balance': 'ವಾಲೆಟ್ ಬ್ಯಾಲೆನ್ಸ್',
            'see_all': 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
            'continue': 'ಮುಂದುವರಿಸಿ',
            'done': 'ಮುಗಿದಿದೆ',
            'next': 'ಮುಂದೆ',
            'skip': 'ಬಿಟ್ಟುಬಿಡಿ',
            'quote1': 'ಪ್ರತಿ ರೂಪಾಯಿಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ. ಪ್ರತಿಯೊಂದು ಕನಸನ್ನೂ ನಿರ್ಮಿಸಿ.',
            'quote2': 'ಬುದ್ಧಿವಂತಿಕೆಯಿಂದ ಖರ್ಚು ಮಾಡಿ. ನಿರಂತರವಾಗಿ ಉಳಿಸಿ.',
            'quote3': 'ಇಂದಿನ ಸಣ್ಣ ಉಳಿತಾಯ, ನಾಳೆಯ ದೊಡ್ಡ ಸ್ವಾತಂತ್ರ್ಯ.',
            'quote4': 'ಬಜೆಟ್ ಎಂದರೆ ನಿಮ್ಮ ಹಣ ಎಲ್ಲಿ ಹೋಗಬೇಕು ಎಂದು ಹೇಳುವುದು.',
            'quote5': 'ಪ್ರತಿ ಖರ್ಚು ಒಂದು ಕಥೆಯನ್ನು ಹೇಳುತ್ತದೆ.',
            'quote6': 'ಹಣ ನಿಮ್ಮನ್ನು ನಿಯಂತ್ರಿಸುವ ಮೊದಲು ನೀವು ಅದನ್ನು ನಿಯಂತ್ರಿಸಿ.',
            'quote7': 'ಆರ್ಥಿಕ ಸ್ವಾತಂತ್ರ್ಯ ಟ್ರ್ಯಾಕಿಂಗ್‌ನಿಂದ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ.',
            'quote8': 'ಉತ್ತಮ ನಾಳೆಗಾಗಿ ಇಂದು ಉಳಿಸಿ.',
            'categories': 'ವರ್ಗಗಳು',
            'new_category': 'ಹೊಸ ವರ್ಗ',
            'add_category': 'ವರ್ಗವನ್ನು ಸೇರಿಸಿ',
            'select_category': 'ವರ್ಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
            'new_subcategory': 'ಹೊಸ ಉಪವರ್ಗ',
            'add_subcategory': 'ಉಪವರ್ಗವನ್ನು ಸೇರಿಸಿ',
            'no_categories_yet': 'ಇನ್ನೂ ವರ್ಗಗಳಿಲ್ಲ',
            'no_subcategories': 'ಉಪವರ್ಗಗಳಿಲ್ಲ',
            'category_exists': 'ವರ್ಗ ಈಗಾಗಲೇ ಇದೆ',
            'subcategory_exists': 'ಉಪವರ್ಗ ಈಗಾಗಲೇ ಇದೆ',
            'category_added': 'ವರ್ಗ ಸೇರಿಸಲಾಗಿದೆ',
            'subcategory_added': 'ಉಪವರ್ಗ ಸೇರಿಸಲಾಗಿದೆ',
              'food': 'ಆಹಾರ',
            'breakfast': 'ಬೆಳಗಿನ ಉಪಹಾರ',
            'lunch': 'ಮಧ್ಯಾಹ್ನದ ಊಟ',
            'dinner': 'ರಾತ್ರಿಯ ಊಟ',
            'snacks': 'ತಿಂಡಿಗಳು',

            'travel': 'ಪ್ರಯಾಣ',
            'bus': 'ಬಸ್',
            'train': 'ರೈಲು',
            'fuel': 'ಇಂಧನ',
            'taxi': 'ಟ್ಯಾಕ್ಸಿ',

            'shopping': 'ಖರೀದಿ',
            'clothes': 'ಬಟ್ಟೆಗಳು',
            'electronics': 'ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್',
            'groceries': 'ಮಳಿಗೆ ಸಾಮಾನು',
            'accessories': 'ಆಕ್ಸೆಸರಿಗಳು',

            'bills': 'ಬಿಲ್ಲುಗಳು',
            'electricity': 'ವಿದ್ಯುತ್',
            'internet': 'ಇಂಟರ್ನೆಟ್',
            'water': 'ನೀರು',
            'mobile_recharge': 'ಮೊಬೈಲ್ ರೀಚಾರ್ಜ್',

            'entertainment': 'ಮನರಂಜನೆ',
            'movies': 'ಚಿತ್ರಗಳು',
            'games': 'ಆಟಗಳು',
            'music': 'ಸಂಗೀತ',
            'ott': 'OTT',

            'health': 'ಆರೋಗ್ಯ',
            'medicine': 'ಔಷಧ',
            'doctor': 'ವೈದ್ಯರು',
            'gym': 'ಜಿಮ್',
            'insurance': 'ವಿಮೆ',

            'education': 'ಶಿಕ್ಷಣ',
            'books': 'ಪುಸ್ತಕಗಳು',
            'fees': 'ಶುಲ್ಕ',
            'courses': 'ಪಠ್ಯಕ್ರಮಗಳು',
            'stationery': 'ಸ್ಟೇಷನರಿ',

            "add_transaction": "ವಹಿವಾಟು ಸೇರಿಸಿ",
  "enter_amount": "ಮೊತ್ತವನ್ನು ನಮೂದಿಸಿ",
 // "income": "ಆದಾಯ",
  //"expense": "ಖರ್ಚು",
  "select_subcategory": "ಉಪವರ್ಗ ಆಯ್ಕೆಮಾಡಿ",
  "save_transaction": "ಉಳಿಸಿ",
  "reports_export": "ವರದಿಗಳು ಮತ್ತು ರಫ್ತು",
  "financial_reports": "ಹಣಕಾಸು ವರದಿಗಳು",
  "report_subtitle": "ದಿನಾಂಕ ಶ್ರೇಣಿಯ ಆಧಾರದಲ್ಲಿ PDF ಮತ್ತು Excel ವರದಿಗಳನ್ನು ರಚಿಸಿ",
  "select_date_range": "ದಿನಾಂಕ ಶ್ರೇಣಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "choose_from_date": "ಆರಂಭ ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ",
  "choose_to_date": "ಅಂತಿಮ ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ",
  "from": "ಇಂದ",
  "to": "ವರೆಗೆ",
  "download_pdf": "PDF ಡೌನ್‌ಲೋಡ್",
  "download_excel": "Excel ಡೌನ್‌ಲೋಡ್",
  "upload_pdf": "PDF ಅಪ್‌ಲೋಡ್",

    //"analytics": "ವಿಶ್ಲೇಷಣೆ",
//"no_data": "ಡೇಟಾ ಇಲ್ಲ",
"financial_overview": "ಆರ್ಥಿಕ ಅವಲೋಕನ",
"category_expense": "ವರ್ಗ ವೆಚ್ಚ",
"daily_expense": "ದೈನಂದಿನ ವೆಚ್ಚಗಳು",
"monthly_expense": "ಮಾಸಿಕ ವೆಚ್ಚಗಳು",
"salary": "ವೇತನ",
"others": "ಇತರೆ",
"smart_wallet": "ಸ್ಮಾರ್ಟ್ ವಾಲೆಟ್",
//'add_transaction': 'ವಹಿವಾಟನ್ನು ಸೇರಿಸಿ',
//'save_transaction': 'লেনদেন সংরক্ষণ করুন',
'track_save_grow': 'ಟ್ರ್ಯಾಕ್ ಮಾಡಿ • ಉಳಿಸಿ • ಬೆಳೆಯಿರಿ',
'wallet_login': 'ವಾಲೆಟ್ ಲಾಗಿನ್',
'username': 'ಬಳಕೆದಾರ ಹೆಸರು',
'password': 'ಪಾಸ್‌ವರ್ಡ್',
'login': 'ಲಾಗಿನ್',
'register_prompt': 'ಖಾತೆ ಇಲ್ಲವೇ? ನೋಂದಣಿ ಮಾಡಿ',
'login_successful': 'ಲಾಗಿನ್ ಯಶಸ್ವಿಯಾಗಿದೆ',
'invalid_credentials': 'ತಪ್ಪಾದ ಬಳಕೆದಾರ ಹೆಸರು ಅಥವಾ ಪಾಸ್‌ವರ್ಡ್',
'enter_credentials': 'ದಯವಿಟ್ಟು ಬಳಕೆದಾರ ಹೆಸರು ಮತ್ತು ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ',

'create_account': 'ಖಾತೆ ರಚಿಸಿ',
'fill_all_fields': 'ದಯವಿಟ್ಟು ಎಲ್ಲಾ ಕ್ಷೇತ್ರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ',
'password_not_match': 'ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ',
'account_created': 'ಖಾತೆ ಯಶಸ್ವಿಯಾಗಿ ರಚಿಸಲಾಗಿದೆ',
'username_exists': 'ಬಳಕೆದಾರ ಹೆಸರು ಈಗಾಗಲೇ ಇದೆ',
'confirm_password': 'ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
'already_have_account': 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ? ಲಾಗಿನ್ ಮಾಡಿ',
"sub_category_expenses": "ಉಪವರ್ಗ ವೆಚ್ಚಗಳು",
"language": "ಭಾಷೆ",
"manage_profiles": "ಪ್ರೊಫೈಲ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
"manage_profiles_desc": "ಪ್ರೊಫೈಲ್ ಬದಲಿಸಿ, ಯೋಜನೆ ರಚಿಸಿ, ಯೋಜನೆ ಅಳಿಸಿ",
"choose_profile": "ಪ್ರೊಫೈಲ್ ಆಯ್ಕೆಮಾಡಿ",
  "choose_workspace": "ನಿಮ್ಮ ಕಾರ್ಯಕ್ಷೇತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ",
  "personal": "ವೈಯಕ್ತಿಕ",
  "manage_personal_expenses": "ವೈಯಕ್ತಿಕ ವೆಚ್ಚಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
  "business": "ವ್ಯವಹಾರ",
  "track_business_finances": "ವ್ಯವಹಾರದ ಹಣಕಾಸುಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
  "projects": "ಯೋಜನೆಗಳು",
  "no_projects_created": "ಯಾವುದೇ ಯೋಜನೆಗಳನ್ನು ರಚಿಸಲಾಗಿಲ್ಲ",
  "create_project": "ಯೋಜನೆ ರಚಿಸಿ",
  "enter_project_name": "ಯೋಜನೆಯ ಹೆಸರನ್ನು ನಮೂದಿಸಿ",
  "project_already_exists": "ಯೋಜನೆ ಈಗಾಗಲೇ ಅಸ್ತಿತ್ವದಲ್ಲಿದೆ",
  //"cancel": "ರದ್ದುಮಾಡಿ",
  "create": "ರಚಿಸಿ"
          },


        //////////////////////////////////////////////////
        // BENGALI
        //////////////////////////////////////////////////

        'bn': {
          'app_name': 'ওয়ালেট উইজ',
          'my_wallet': 'আমার ওয়ালেট',
          'income': 'আয়',
          'expense': 'খরচ',
          'weekly': 'সাপ্তাহিক',
          'monthly': 'মাসিক',
          'yearly': 'বার্ষিক',
          'total': 'মোট',
          'recent_transactions': 'সাম্প্রতিক লেনদেন',
          'view_all': 'সব দেখুন',
          'home': 'হোম',
          'stats': 'পরিসংখ্যান',
          'category': 'বিভাগ',
          'settings': 'সেটিংস',
          'add': 'যোগ করুন',
          'balance': 'ব্যালেন্স',
          'currency': 'মুদ্রা',
          'select_language': 'ভাষা নির্বাচন করুন',
          'select_currency': 'মুদ্রা নির্বাচন করুন',
          'save': 'সংরক্ষণ করুন',
          'cancel': 'বাতিল',
          'delete': 'মুছুন',
          'edit': 'সম্পাদনা',
          'search': 'অনুসন্ধান',
          'welcome': 'স্বাগতম',
          'transaction': 'লেনদেন',
          'no_data': 'কোনো তথ্য পাওয়া যায়নি',
          'quote1': 'প্রতিটি টাকা ট্র্যাক করুন। প্রতিটি স্বপ্ন গড়ুন।',
          'quote2': 'বুদ্ধিমানের মতো খরচ করুন। নিয়মিত সঞ্চয় করুন।',
          'quote3': 'আজকের ছোট সঞ্চয়, আগামীর বড় স্বাধীনতা।',
          'quote4': 'বাজেট আপনার অর্থকে সঠিক পথে পরিচালিত করে।',
          'quote5': 'প্রতিটি খরচ একটি গল্প বলে।',
          'quote6': 'অর্থ আপনাকে নিয়ন্ত্রণ করার আগে আপনি অর্থকে নিয়ন্ত্রণ করুন।',
          'quote7': 'আর্থিক স্বাধীনতা ট্র্যাকিং দিয়ে শুরু হয়।',
          'quote8': 'ভাল আগামীকালের জন্য আজ সঞ্চয় করুন।',
          'categories': 'বিভাগসমূহ',
          'new_category': 'নতুন বিভাগ',
          'add_category': 'বিভাগ যোগ করুন',
          'select_category': 'বিভাগ নির্বাচন করুন',
          'new_subcategory': 'নতুন উপবিভাগ',
          'add_subcategory': 'উপবিভাগ যোগ করুন',
          'no_categories_yet': 'এখনও কোনো বিভাগ নেই',
          'no_subcategories': 'কোনো উপবিভাগ নেই',
          'category_exists': 'বিভাগ ইতিমধ্যেই আছে',
          'subcategory_exists': 'উপবিভাগ ইতিমধ্যেই আছে',
          'category_added': 'বিভাগ যোগ করা হয়েছে',
          'subcategory_added': 'উপবিভাগ যোগ করা হয়েছে',
            'food': 'খাদ্য',
            'breakfast': 'সকালের নাস্তা',
            'lunch': 'দুপুরের খাবার',
            'dinner': 'রাতের খাবার',
            'snacks': 'হালকা খাবার',

            'travel': 'ভ্রমণ',
            'bus': 'বাস',
            'train': 'ট্রেন',
            'fuel': 'জ্বালানি',
            'taxi': 'ট্যাক্সি',

            'shopping': 'কেনাকাটা',
            'clothes': 'কাপড়',
            'electronics': 'ইলেকট্রনিক্স',
            'groceries': 'মুদিখানা',
            'accessories': 'অ্যাক্সেসরিজ',

            'bills': 'বিল',
            'electricity': 'বিদ্যুৎ',
            'internet': 'ইন্টারনেট',
            'water': 'পানি',
            'mobile_recharge': 'মোবাইল রিচার্জ',

            'entertainment': 'বিনোদন',
            'movies': 'সিনেমা',
            'games': 'গেমস',
            'music': 'সঙ্গীত',
            'ott': 'OTT',

            'health': 'স্বাস্থ্য',
            'medicine': 'ওষুধ',
            'doctor': 'ডাক্তার',
            'gym': 'জিম',
            'insurance': 'বীমা',

            'education': 'শিক্ষা',
            'books': 'বই',
            'fees': 'ফি',
            'courses': 'কোর্স',
            'stationery': 'স্টেশনারি',
            "add_transaction": "লেনদেন যোগ করুন",
  "enter_amount": "পরিমাণ লিখুন",
  //"income": "আয়",
  //"expense": "খরচ",
  "select_subcategory": "সাবক্যাটাগরি নির্বাচন করুন",
  "save_transaction": "সংরক্ষণ করুন",
  "reports_export": "রিপোর্ট ও এক্সপোর্ট",
  "financial_reports": "আর্থিক রিপোর্ট",
  "report_subtitle": "তারিখ অনুযায়ী PDF এবং Excel রিপোর্ট তৈরি করুন",
  "select_date_range": "তারিখ নির্বাচন করুন",
  "choose_from_date": "শুরুর তারিখ নির্বাচন করুন",
  "choose_to_date": "শেষ তারিখ নির্বাচন করুন",
  "from": "থেকে",
  "to": "পর্যন্ত",
  "download_pdf": "PDF ডাউনলোড",
  "download_excel": "Excel ডাউনলোড",
  "upload_pdf": "PDF আপলোড",

    //"analytics": "বিশ্লেষণ",
//"no_data": "কোনো তথ্য নেই",
"financial_overview": "আর্থিক সারাংশ",
"category_expense": "শ্রেণি ব্যয়",
"daily_expense": "দৈনিক ব্যয়",
"monthly_expense": "মাসিক ব্যয়",
"salary": "বেতন",
"others": "অন্যান্য",
"smart_wallet": "স্মার্ট ওয়ালেট",
//'add_transaction': 'লেনদেন যোগ করুন',
//'save_transaction': 'লেনদেন সংরক্ষণ করুন',
'track_save_grow': 'ট্র্যাক করুন • সঞ্চয় করুন • উন্নতি করুন',
'wallet_login': 'ওয়ালেট লগইন',
'username': 'ব্যবহারকারীর নাম',
'password': 'পাসওয়ার্ড',
'login': 'লগইন',
'register_prompt': 'অ্যাকাউন্ট নেই? নিবন্ধন করুন',
'login_successful': 'লগইন সফল',
'invalid_credentials': 'ভুল ব্যবহারকারীর নাম বা পাসওয়ার্ড',
'enter_credentials': 'অনুগ্রহ করে ব্যবহারকারীর নাম এবং পাসওয়ার্ড লিখুন',

'create_account': 'অ্যাকাউন্ট তৈরি করুন',
'fill_all_fields': 'অনুগ্রহ করে সব ঘর পূরণ করুন',
'password_not_match': 'পাসওয়ার্ড মিলছে না',
'account_created': 'অ্যাকাউন্ট সফলভাবে তৈরি হয়েছে',
'username_exists': 'ব্যবহারকারীর নাম ইতিমধ্যে বিদ্যমান',
'confirm_password': 'পাসওয়ার্ড নিশ্চিত করুন',
'already_have_account': 'ইতিমধ্যে অ্যাকাউন্ট আছে? লগইন করুন',
"sub_category_expenses": "উপ-শ্রেণির খরচ",
"language": "ভাষা",
"manage_profiles": "প্রোফাইল পরিচালনা",
"manage_profiles_desc": "প্রোফাইল পরিবর্তন করুন, প্রকল্প তৈরি করুন, প্রকল্প মুছুন",
"choose_profile": "প্রোফাইল নির্বাচন করুন",
  "choose_workspace": "আপনার ওয়ার্কস্পেস নির্বাচন করুন",
  "personal": "ব্যক্তিগত",
  "manage_personal_expenses": "ব্যক্তিগত খরচ পরিচালনা করুন",
  "business": "ব্যবসা",
  "track_business_finances": "ব্যবসার আর্থিক অবস্থা ট্র্যাক করুন",
  "projects": "প্রকল্পসমূহ",
  "no_projects_created": "কোনো প্রকল্প তৈরি করা হয়নি",
  "create_project": "প্রকল্প তৈরি করুন",
  "enter_project_name": "প্রকল্পের নাম লিখুন",
  "project_already_exists": "প্রকল্প ইতিমধ্যেই বিদ্যমান",
  //"cancel": "বাতিল",
  "create": "তৈরি করুন"
        },

        //////////////////////////////////////////////////
        // GUJARATI
        //////////////////////////////////////////////////

        'gu': {
          'app_name': 'વૉલેટ વિઝ',
          'my_wallet': 'મારું વૉલેટ',
          'income': 'આવક',
          'expense': 'ખર્ચ',
          'weekly': 'સાપ્તાહિક',
          'monthly': 'માસિક',
          'yearly': 'વાર્ષિક',
          'total': 'કુલ',
          'recent_transactions': 'તાજેતરના વ્યવહારો',
          'view_all': 'બધું જુઓ',
          'home': 'હોમ',
          'stats': 'આંકડા',
          'category': 'શ્રેણી',
          'settings': 'સેટિંગ્સ',
          'add': 'ઉમેરો',
          'balance': 'બેલેન્સ',
          'currency': 'ચલણ',
          'select_language': 'ભાષા પસંદ કરો',
          'select_currency': 'ચલણ પસંદ કરો',
          'save': 'સાચવો',
          'cancel': 'રદ કરો',
          'delete': 'કાઢી નાખો',
          'edit': 'ફેરફાર કરો',
          'search': 'શોધો',
          'welcome': 'સ્વાગત છે',
          'transaction': 'વ્યવહાર',
          'no_data': 'માહિતી મળી નથી',
          'quote1': 'દરેક રૂપિયાને ટ્રેક કરો. દરેક સપનાને સાકાર કરો.',
          'quote2': 'સમજદારીથી ખર્ચ કરો. સતત બચત કરો.',
          'quote3': 'આજની નાની બચત, આવતીકાલની મોટી સ્વતંત્રતા.',
          'quote4': 'બજેટ એટલે તમારા પૈસા ક્યાં જવા જોઈએ તે કહેવું.',
          'quote5': 'દરેક ખર્ચ એક વાર્તા કહે છે.',
          'quote6': 'પૈસા તમને નિયંત્રિત કરે તે પહેલાં તમે પૈસાને નિયંત્રિત કરો.',
          'quote7': 'આર્થિક સ્વતંત્રતા ટ્રેકિંગથી શરૂ થાય છે.',
          'quote8': 'સારા આવતીકાલ માટે આજે બચત કરો.',
          'categories': 'શ્રેણીઓ',
          'new_category': 'નવી શ્રેણી',
          'add_category': 'શ્રેણી ઉમેરો',
          'select_category': 'શ્રેણી પસંદ કરો',
          'new_subcategory': 'નવી ઉપશ્રેણી',
          'add_subcategory': 'ઉપશ્રેણી ઉમેરો',
          'no_categories_yet': 'હજુ સુધી કોઈ શ્રેણી નથી',
          'no_subcategories': 'કોઈ ઉપશ્રેણી નથી',
          'category_exists': 'શ્રેણી પહેલેથી જ હાજર છે',
          'subcategory_exists': 'ઉપશ્રેણી પહેલેથી જ હાજર છે',
          'category_added': 'શ્રેણી ઉમેરાઈ ગઈ',
          'subcategory_added': 'ઉપશ્રેણી ઉમેરાઈ ગઈ',
          'food': 'ખોરાક',
          'breakfast': 'સવારનો નાસ્તો',
          'lunch': 'બપોરનું ભોજન',
          'dinner': 'રાત્રિભોજન',
          'snacks': 'નાસ્તા',

          'travel': 'મુસાફરી',
          'bus': 'બસ',
          'train': 'ટ્રેન',
          'fuel': 'ઇંધણ',
          'taxi': 'ટેક્સી',

          'shopping': 'ખરીદી',
          'clothes': 'કપડાં',
          'electronics': 'ઇલેક્ટ્રોનિક્સ',
          'groceries': 'કિરાણા',
          'accessories': 'એસેસરીઝ',

          'bills': 'બિલ્સ',
          'electricity': 'વીજળી',
          'internet': 'ઇન્ટરનેટ',
          'water': 'પાણી',
          'mobile_recharge': 'મોબાઇલ રિચાર્જ',

          'entertainment': 'મનોરંજન',
          'movies': 'ફિલ્મો',
          'games': 'રમતો',
          'music': 'સંગીત',
          'ott': 'OTT',

          'health': 'આરોગ્ય',
          'medicine': 'દવા',
          'doctor': 'ડૉક્ટર',
          'gym': 'જિમ',
          'insurance': 'વીમા',

          'education': 'શિક્ષણ',
          'books': 'પુસ્તકો',
          'fees': 'ફી',
          'courses': 'કોર્સ',
          'stationery': 'સ્ટેશનરી',
            "add_transaction": "વ્યવહાર ઉમેરો",
  "enter_amount": "રકમ દાખલ કરો",
  //"income": "આવક",
  //"expense": "ખર્ચ",
  "select_subcategory": "ઉપવર્ગ પસંદ કરો",
  "save_transaction": "સાચવો",
  "reports_export": "રિપોર્ટ અને એક્સપોર્ટ",
  "financial_reports": "આર્થિક રિપોર્ટ",
  "report_subtitle": "તારીખ પ્રમાણે PDF અને Excel રિપોર્ટ બનાવો",
  "select_date_range": "તારીખ પસંદ કરો",
  "choose_from_date": "પ્રારંભ તારીખ પસંદ કરો",
  "choose_to_date": "અંતિમ તારીખ પસંદ કરો",
  "from": "થી",
  "to": "સુધી",
  "download_pdf": "PDF ડાઉનલોડ",
  "download_excel": "Excel ડાઉનલોડ",
  "upload_pdf": "PDF અપલોડ",
    //"analytics": "વિશ્લેષણ",
//"no_data": "કોઈ ડેટા નથી",
"financial_overview": "આર્થિક અવલોકન",
"category_expense": "શ્રેણી ખર્ચ",
"daily_expense": "દૈનિક ખર્ચ",
"monthly_expense": "માસિક ખર્ચ",
"salary": "પગાર",
"others": "અન્ય",
"smart_wallet": "સ્માર્ટ વૉલેટ",
//'add_transaction': 'વ્યવહાર ઉમેરો', 
//'save_transaction': 'વ્યવહાર સાચવો',
'track_save_grow': 'ટ્રેક કરો • બચત કરો • વિકાસ કરો',
'wallet_login': 'વૉલેટ લૉગિન',
'username': 'વપરાશકર્તા નામ',
'password': 'પાસવર્ડ',
'login': 'લૉગિન',
'register_prompt': 'એકાઉન્ટ નથી? નોંધણી કરો',
'login_successful': 'લૉગિન સફળ',
'invalid_credentials': 'ખોટું વપરાશકર્તા નામ અથવા પાસવર્ડ',
'enter_credentials': 'કૃપા કરીને વપરાશકર્તા નામ અને પાસવર્ડ દાખલ કરો',

'create_account': 'એકાઉન્ટ બનાવો',
'fill_all_fields': 'કૃપા કરીને બધા ફીલ્ડ ભરો',
'password_not_match': 'પાસવર્ડ મેળ ખાતા નથી',
'account_created': 'એકાઉન્ટ સફળતાપૂર્વક બનાવાયું',
'username_exists': 'વપરાશકર્તા નામ પહેલેથી જ અસ્તિત્વમાં છે',
'confirm_password': 'પાસવર્ડની પુષ્ટિ કરો',
'already_have_account': 'પહેલેથી એકાઉન્ટ છે? લૉગિન કરો',
"sub_category_expenses": "ઉપશ્રેણી ખર્ચ",
"language": "ભાષા",
"manage_profiles": "પ્રોફાઇલ મેનેજ કરો",
"manage_profiles_desc": "પ્રોફાઇલ બદલો, પ્રોજેક્ટ બનાવો, પ્રોજેક્ટ કાઢી નાખો",
"choose_profile": "પ્રોફાઇલ પસંદ કરો",
  "choose_workspace": "તમારું વર્કસ્પેસ પસંદ કરો",
  "personal": "વ્યક્તિગત",
  "manage_personal_expenses": "વ્યક્તિગત ખર્ચનું સંચાલન કરો",
  "business": "વ્યવસાય",
  "track_business_finances": "વ્યવસાયિક નાણાંનું ટ્રેકિંગ કરો",
  "projects": "પ્રોજેક્ટ્સ",
  "no_projects_created": "કોઈ પ્રોજેક્ટ બનાવવામાં આવ્યો નથી",
  "create_project": "પ્રોજેક્ટ બનાવો",
  "enter_project_name": "પ્રોજેક્ટનું નામ દાખલ કરો",
  "project_already_exists": "પ્રોજેક્ટ પહેલેથી અસ્તિત્વમાં છે",
  //"cancel": "રદ કરો",
  "create": "બનાવો"
        },

        //////////////////////////////////////////////////
        // MARATHI
        //////////////////////////////////////////////////

        'mr': {
          'app_name': 'वॉलेट विझ',
          'my_wallet': 'माझे वॉलेट',
          'income': 'उत्पन्न',
          'expense': 'खर्च',
          'weekly': 'साप्ताहिक',
          'monthly': 'मासिक',
          'yearly': 'वार्षिक',
          'total': 'एकूण',
          'recent_transactions': 'अलीकडील व्यवहार',
          'view_all': 'सर्व पहा',
          'home': 'मुख्यपृष्ठ',
          'stats': 'आकडेवारी',
          'category': 'श्रेणी',
          'settings': 'सेटिंग्ज',
          'add': 'जोडा',
          'balance': 'शिल्लक',
          'currency': 'चलन',
          'select_language': 'भाषा निवडा',
          'select_currency': 'चलन निवडा',
          'save': 'जतन करा',
          'cancel': 'रद्द करा',
          'delete': 'हटवा',
          'edit': 'संपादित करा',
          'search': 'शोधा',
          'welcome': 'स्वागत आहे',
          'transaction': 'व्यवहार',
          'no_data': 'डेटा सापडला नाही',
          'quote1': 'प्रत्येक रुपयाचा हिशोब ठेवा. प्रत्येक स्वप्न साकार करा.',
          'quote2': 'शहाणपणाने खर्च करा. नियमित बचत करा.',
          'quote3': 'आजची छोटी बचत, उद्याचे मोठे स्वातंत्र्य.',
          'quote4': 'बजेट म्हणजे तुमचे पैसे कुठे जायचे हे सांगणे.',
          'quote5': 'प्रत्येक खर्च एक कथा सांगतो.',
          'quote6': 'पैसे तुम्हाला नियंत्रित करण्यापूर्वी तुम्ही पैशांना नियंत्रित करा.',
          'quote7': 'आर्थिक स्वातंत्र्य ट्रॅकिंगपासून सुरू होते.',
          'quote8': 'चांगल्या उद्यासाठी आज बचत करा.',
          'categories': 'श्रेण्या',
          'new_category': 'नवीन श्रेणी',
          'add_category': 'श्रेणी जोडा',
          'select_category': 'श्रेणी निवडा',
          'new_subcategory': 'नवीन उपश्रेणी',
          'add_subcategory': 'उपश्रेणी जोडा',
          'no_categories_yet': 'अद्याप कोणत्याही श्रेण्या नाहीत',
          'no_subcategories': 'कोणत्याही उपश्रेण्या नाहीत',
          'category_exists': 'श्रेणी आधीपासून अस्तित्वात आहे',
          'subcategory_exists': 'उपश्रेणी आधीपासून अस्तित्वात आहे',
          'category_added': 'श्रेणी जोडली गेली',
          'subcategory_added': 'उपश्रेणी जोडली गेली',
            'food': 'अन्न',
            'breakfast': 'नाश्ता',
            'lunch': 'दुपारचे जेवण',
            'dinner': 'रात्रीचे जेवण',
            'snacks': 'खाऊ',

            'travel': 'प्रवास',
            'bus': 'बस',
            'train': 'रेल्वे',
            'fuel': 'इंधन',
            'taxi': 'टॅक्सी',

            'shopping': 'खरेदी',
            'clothes': 'कपडे',
            'electronics': 'इलेक्ट्रॉनिक्स',
            'groceries': 'किराणा',
            'accessories': 'अॅक्सेसरीज',

            'bills': 'बिले',
            'electricity': 'वीज',
            'internet': 'इंटरनेट',
            'water': 'पाणी',
            'mobile_recharge': 'मोबाईल रिचार्ज',

            'entertainment': 'मनोरंजन',
            'movies': 'चित्रपट',
            'games': 'खेळ',
            'music': 'संगीत',
            'ott': 'OTT',

            'health': 'आरोग्य',
            'medicine': 'औषध',
            'doctor': 'डॉक्टर',
            'gym': 'जिम',
            'insurance': 'विमा',

            'education': 'शिक्षण',
            'books': 'पुस्तके',
            'fees': 'फी',
            'courses': 'अभ्यासक्रम',
            'stationery': 'स्टेशनरी',
             "add_transaction": "व्यवहार जोडा",
  "enter_amount": "रक्कम भरा",
  //"income": "उत्पन्न",
  //"expense": "खर्च",
  "select_subcategory": "उपश्रेणी निवडा",
  "save_transaction": "जतन करा",
  "reports_export": "अहवाल आणि निर्यात",
  "financial_reports": "आर्थिक अहवाल",
  "report_subtitle": "तारखेनुसार PDF आणि Excel अहवाल तयार करा",
  "select_date_range": "तारीख निवडा",
  "choose_from_date": "सुरुवातीची तारीख निवडा",
  "choose_to_date": "शेवटची तारीख निवडा",
  "from": "पासून",
  "to": "पर्यंत",
  "download_pdf": "PDF डाउनलोड",
  "download_excel": "Excel डाउनलोड",
  "upload_pdf": "PDF अपलोड",
  //"analytics": "विश्लेषण",
//"no_data": "डेटा नाही",
"financial_overview": "आर्थिक आढावा",
"category_expense": "श्रेणी खर्च",
"daily_expense": "दैनिक खर्च",
"monthly_expense": "मासिक खर्च",
"salary": "पगार",
"others": "इतर",
"smart_wallet": "स्मार्ट वॉलेट",
//'add_transaction': 'व्यवहार जोडा',
//'save_transaction': 'व्यवहार जतन करा',
'track_save_grow': 'मागोवा घ्या • बचत करा • प्रगती करा',
'wallet_login': 'वॉलेट लॉगिन',
'username': 'वापरकर्तानाव',
'password': 'पासवर्ड',
'login': 'लॉगिन',
'register_prompt': 'खाते नाही? नोंदणी करा',
'login_successful': 'लॉगिन यशस्वी',
'invalid_credentials': 'चुकीचे वापरकर्तानाव किंवा पासवर्ड',
'enter_credentials': 'कृपया वापरकर्तानाव आणि पासवर्ड प्रविष्ट करा',

'create_account': 'खाते तयार करा',
'fill_all_fields': 'कृपया सर्व फील्ड भरा',
'password_not_match': 'पासवर्ड जुळत नाहीत',
'account_created': 'खाते यशस्वीरित्या तयार झाले',
'username_exists': 'वापरकर्तानाव आधीच अस्तित्वात आहे',
'confirm_password': 'पासवर्डची पुष्टी करा',
'already_have_account': 'आधीपासून खाते आहे? लॉगिन करा',
"sub_category_expenses": "उपश्रेणी खर्च",
"language": "भाषा",
"manage_profiles": "प्रोफाइल व्यवस्थापन",
"manage_profiles_desc": "प्रोफाइल बदला, प्रकल्प तयार करा, प्रकल्प हटवा",
"choose_profile": "प्रोफाइल निवडा",
  "choose_workspace": "तुमचे कार्यक्षेत्र निवडा",
  "personal": "वैयक्तिक",
  "manage_personal_expenses": "वैयक्तिक खर्च व्यवस्थापित करा",
  "business": "व्यवसाय",
  "track_business_finances": "व्यवसाय आर्थिक व्यवहारांचा मागोवा घ्या",
  "projects": "प्रकल्प",
  "no_projects_created": "कोणतेही प्रकल्प तयार केलेले नाहीत",
  "create_project": "प्रकल्प तयार करा",
  "enter_project_name": "प्रकल्पाचे नाव प्रविष्ट करा",
  "project_already_exists": "प्रकल्प आधीपासून अस्तित्वात आहे",
  //"cancel": "रद्द करा",
  "create": "तयार करा"

        },

        //////////////////////////////////////////////////
        // PUNJABI
        //////////////////////////////////////////////////

        'pa': {
          'app_name': 'ਵਾਲਿਟ ਵਿਜ਼',
          'my_wallet': 'ਮੇਰਾ ਵਾਲਿਟ',
          'income': 'ਆਮਦਨ',
          'expense': 'ਖਰਚ',
          'weekly': 'ਹਫਤਾਵਾਰੀ',
          'monthly': 'ਮਹੀਨਾਵਾਰ',
          'yearly': 'ਸਾਲਾਨਾ',
          'total': 'ਕੁੱਲ',
          'recent_transactions': 'ਹਾਲੀਆ ਲੈਣ-ਦੇਣ',
          'view_all': 'ਸਭ ਵੇਖੋ',
          'home': 'ਹੋਮ',
          'stats': 'ਅੰਕੜੇ',
          'category': 'ਸ਼੍ਰੇਣੀ',
          'settings': 'ਸੈਟਿੰਗਜ਼',
          'add': 'ਸ਼ਾਮਲ ਕਰੋ',
          'balance': 'ਬਕਾਇਆ',
          'currency': 'ਮੁਦਰਾ',
          'select_language': 'ਭਾਸ਼ਾ ਚੁਣੋ',
          'select_currency': 'ਮੁਦਰਾ ਚੁਣੋ',
          'save': 'ਸੰਭਾਲੋ',
          'cancel': 'ਰੱਦ ਕਰੋ',
          'delete': 'ਮਿਟਾਓ',
          'edit': 'ਸੋਧੋ',
          'search': 'ਖੋਜੋ',
          'welcome': 'ਸੁਆਗਤ ਹੈ',
          'transaction': 'ਲੈਣ-ਦੇਣ',
          'no_data': 'ਕੋਈ ਡਾਟਾ ਨਹੀਂ ਮਿਲਿਆ',
          'quote1': 'ਹਰ ਰੁਪਏ ਦਾ ਹਿਸਾਬ ਰੱਖੋ। ਹਰ ਸੁਪਨਾ ਬਣਾਓ।',
          'quote2': 'ਸਮਝਦਾਰੀ ਨਾਲ ਖਰਚ ਕਰੋ। ਨਿਰੰਤਰ ਬਚਤ ਕਰੋ।',
          'quote3': 'ਅੱਜ ਦੀ ਛੋਟੀ ਬਚਤ, ਕੱਲ੍ਹ ਦੀ ਵੱਡੀ ਆਜ਼ਾਦੀ।',
          'quote4': 'ਬਜਟ ਤੁਹਾਡੇ ਪੈਸੇ ਨੂੰ ਸਹੀ ਦਿਸ਼ਾ ਦਿੰਦਾ ਹੈ।',
          'quote5': 'ਹਰ ਖਰਚ ਇੱਕ ਕਹਾਣੀ ਦੱਸਦਾ ਹੈ।',
          'quote6': 'ਪੈਸਾ ਤੁਹਾਨੂੰ ਕੰਟਰੋਲ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਤੁਸੀਂ ਪੈਸੇ ਨੂੰ ਕੰਟਰੋਲ ਕਰੋ।',
          'quote7': 'ਵਿੱਤੀ ਆਜ਼ਾਦੀ ਟ੍ਰੈਕਿੰਗ ਨਾਲ ਸ਼ੁਰੂ ਹੁੰਦੀ ਹੈ।',
          'quote8': 'ਚੰਗੇ ਕੱਲ੍ਹ ਲਈ ਅੱਜ ਬਚਤ ਕਰੋ।',

            'categories': 'ਸ਼੍ਰੇਣੀਆਂ',
            'new_category': 'ਨਵੀਂ ਸ਼੍ਰੇਣੀ',
            'add_category': 'ਸ਼੍ਰੇਣੀ ਸ਼ਾਮਲ ਕਰੋ',
            'select_category': 'ਸ਼੍ਰੇਣੀ ਚੁਣੋ',
            'new_subcategory': 'ਨਵੀਂ ਉਪਸ਼੍ਰੇਣੀ',
            'add_subcategory': 'ਉਪਸ਼੍ਰੇਣੀ ਸ਼ਾਮਲ ਕਰੋ',
            'no_categories_yet': 'ਹਾਲੇ ਕੋਈ ਸ਼੍ਰੇਣੀਆਂ ਨਹੀਂ',
            'no_subcategories': 'ਕੋਈ ਉਪਸ਼੍ਰੇਣੀਆਂ ਨਹੀਂ',
            'category_exists': 'ਸ਼੍ਰੇਣੀ ਪਹਿਲਾਂ ਹੀ ਮੌਜੂਦ ਹੈ',
            'subcategory_exists': 'ਉਪਸ਼੍ਰੇਣੀ ਪਹਿਲਾਂ ਹੀ ਮੌਜੂਦ ਹੈ',
            'category_added': 'ਸ਼੍ਰੇਣੀ ਸ਼ਾਮਲ ਕੀਤੀ ਗਈ',
            'subcategory_added': 'ਉਪਸ਼੍ਰੇਣੀ ਸ਼ਾਮਲ ਕੀਤੀ ਗਈ',
            
            'food': 'ਭੋਜਨ',
            'breakfast': 'ਨਾਸਤਾ',
            'lunch': 'ਦੁਪਹਿਰ ਦਾ ਖਾਣਾ',
            'dinner': 'ਰਾਤ ਦਾ ਖਾਣਾ',
            'snacks': 'ਹਲਕਾ ਖਾਣਾ',

            'travel': 'ਯਾਤਰਾ',
            'bus': 'ਬੱਸ',
            'train': 'ਰੇਲਗੱਡੀ',
            'fuel': 'ਇੰਧਨ',
            'taxi': 'ਟੈਕਸੀ',

            'shopping': 'ਖਰੀਦਦਾਰੀ',
            'clothes': 'ਕੱਪੜੇ',
            'electronics': 'ਇਲੈਕਟ੍ਰਾਨਿਕਸ',
            'groceries': 'ਕਿਰਾਣਾ',
            'accessories': 'ਐਕਸੈਸਰੀਜ਼',

            'bills': 'ਬਿੱਲ',
            'electricity': 'ਬਿਜਲੀ',
            'internet': 'ਇੰਟਰਨੈੱਟ',
            'water': 'ਪਾਣੀ',
            'mobile_recharge': 'ਮੋਬਾਈਲ ਰੀਚਾਰਜ',

            'entertainment': 'ਮਨੋਰੰਜਨ',
            'movies': 'ਫਿਲਮਾਂ',
            'games': 'ਖੇਡਾਂ',
            'music': 'ਸੰਗੀਤ',
            'ott': 'OTT',

            'health': 'ਸਿਹਤ',
            'medicine': 'ਦਵਾਈ',
            'doctor': 'ਡਾਕਟਰ',
            'gym': 'ਜਿਮ',
            'insurance': 'ਬੀਮਾ',

            'education': 'ਸਿੱਖਿਆ',
            'books': 'ਕਿਤਾਬਾਂ',
            'fees': 'ਫੀਸ',
            'courses': 'ਕੋਰਸ',
            'stationery': 'ਸਟੇਸ਼ਨਰੀ',
            "add_transaction": "ਲੈਣ-ਦੇਣ ਸ਼ਾਮਲ ਕਰੋ",
  "enter_amount": "ਰਕਮ ਦਰਜ ਕਰੋ",
  //"income": "ਆਮਦਨ",
  //"expense": "ਖਰਚ",
  "select_subcategory": "ਉਪਸ਼੍ਰੇਣੀ ਚੁਣੋ",
  "save_transaction": "ਸੇਵ ਕਰੋ",
  "reports_export": "ਰਿਪੋਰਟ ਅਤੇ ਐਕਸਪੋਰਟ",
  "financial_reports": "ਵਿੱਤੀ ਰਿਪੋਰਟ",
  "report_subtitle": "ਤਾਰੀਖ ਅਨੁਸਾਰ PDF ਅਤੇ Excel ਰਿਪੋਰਟ ਬਣਾਓ",
  "select_date_range": "ਤਾਰੀਖ ਚੁਣੋ",
  "choose_from_date": "ਸ਼ੁਰੂਆਤੀ ਤਾਰੀਖ",
  "choose_to_date": "ਅੰਤਿਮ ਤਾਰੀਖ",
  "from": "ਤੋਂ",
  "to": "ਤੱਕ",
  "download_pdf": "PDF ਡਾਊਨਲੋਡ",
  "download_excel": "Excel ਡਾਊਨਲੋਡ",
  "upload_pdf": "PDF ਅਪਲੋਡ",
    //"analytics": "ਵਿਸ਼ਲੇਸ਼ਣ",
//"no_data": "ਕੋਈ ਡਾਟਾ ਨਹੀਂ",
"financial_overview": "ਵਿੱਤੀ ਝਲਕ",
"category_expense": "ਸ਼੍ਰੇਣੀ ਖਰਚ",
"daily_expense": "ਰੋਜ਼ਾਨਾ ਖਰਚ",
"monthly_expense": "ਮਾਸਿਕ ਖਰਚ",
"salary": "ਤਨਖਾਹ",
"others": "ਹੋਰ",
"smart_wallet": "ਸਮਾਰਟ ਵਾਲਿਟ",
//'add_transaction': 'ਲੈਣ-ਦੇਣ ਸ਼ਾਮਲ ਕਰੋ',
//'save_transaction': 'ਲੈਣ-ਦੇਣ ਸੰਭਾਲੋ',
'track_save_grow': 'ਟਰੈਕ ਕਰੋ • ਬਚਤ ਕਰੋ • ਵਧੋ',
'wallet_login': 'ਵਾਲਿਟ ਲੌਗਇਨ',
'username': 'ਯੂਜ਼ਰਨੇਮ',
'password': 'ਪਾਸਵਰਡ',
'login': 'ਲੌਗਇਨ',
'register_prompt': 'ਖਾਤਾ ਨਹੀਂ ਹੈ? ਰਜਿਸਟਰ ਕਰੋ',
'login_successful': 'ਲੌਗਇਨ ਸਫਲ',
'invalid_credentials': 'ਗਲਤ ਯੂਜ਼ਰਨੇਮ ਜਾਂ ਪਾਸਵਰਡ',
'enter_credentials': 'ਕਿਰਪਾ ਕਰਕੇ ਯੂਜ਼ਰਨੇਮ ਅਤੇ ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ',

'create_account': 'ਖਾਤਾ ਬਣਾਓ',
'fill_all_fields': 'ਕਿਰਪਾ ਕਰਕੇ ਸਾਰੇ ਖੇਤਰ ਭਰੋ',
'password_not_match': 'ਪਾਸਵਰਡ ਮੇਲ ਨਹੀਂ ਖਾਂਦੇ',
'account_created': 'ਖਾਤਾ ਸਫਲਤਾਪੂਰਵਕ ਬਣ ਗਿਆ',
'username_exists': 'ਯੂਜ਼ਰਨੇਮ ਪਹਿਲਾਂ ਹੀ ਮੌਜੂਦ ਹੈ',
'confirm_password': 'ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
'already_have_account': 'ਕੀ ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ? ਲਾਗਇਨ ਕਰੋ',
"sub_category_expenses": "ਉਪ-ਸ਼੍ਰੇਣੀ ਖਰਚੇ",
"language": "ਭਾਸ਼ਾ",
"manage_profiles": "ਪ੍ਰੋਫਾਈਲ ਪ੍ਰਬੰਧਨ",
"manage_profiles_desc": "ਪ੍ਰੋਫਾਈਲ ਬਦਲੋ, ਪ੍ਰੋਜੈਕਟ ਬਣਾਓ, ਪ੍ਰੋਜੈਕਟ ਮਿਟਾਓ",
"choose_profile": "ਪ੍ਰੋਫਾਈਲ ਚੁਣੋ",
  "choose_workspace": "ਆਪਣਾ ਵਰਕਸਪੇਸ ਚੁਣੋ",
  "personal": "ਨਿੱਜੀ",
  "manage_personal_expenses": "ਨਿੱਜੀ ਖਰਚੇ ਸੰਭਾਲੋ",
  "business": "ਕਾਰੋਬਾਰ",
  "track_business_finances": "ਕਾਰੋਬਾਰੀ ਵਿੱਤ ਦਾ ਰਿਕਾਰਡ ਰੱਖੋ",
  "projects": "ਪ੍ਰੋਜੈਕਟ",
  "no_projects_created": "ਕੋਈ ਪ੍ਰੋਜੈਕਟ ਨਹੀਂ ਬਣਾਇਆ ਗਿਆ",
  "create_project": "ਪ੍ਰੋਜੈਕਟ ਬਣਾਓ",
  "enter_project_name": "ਪ੍ਰੋਜੈਕਟ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ",
  "project_already_exists": "ਪ੍ਰੋਜੈਕਟ ਪਹਿਲਾਂ ਹੀ ਮੌਜੂਦ ਹੈ",
  //"cancel": "ਰੱਦ ਕਰੋ",
  "create": "ਬਣਾਓ"
        },

        //////////////////////////////////////////////////
        // URDU
        //////////////////////////////////////////////////

        'ur': {
          'app_name': 'والیٹ وز',
          'my_wallet': 'میرا والیٹ',
          'income': 'آمدنی',
          'expense': 'خرچ',
          'weekly': 'ہفتہ وار',
          'monthly': 'ماہانہ',
          'yearly': 'سالانہ',
          'total': 'کل',
          'recent_transactions': 'حالیہ لین دین',
          'view_all': 'سب دیکھیں',
          'home': 'ہوم',
          'stats': 'اعداد و شمار',
          'category': 'قسم',
          'settings': 'ترتیبات',
          'add': 'شامل کریں',
          'balance': 'بیلنس',
          'currency': 'کرنسی',
          'select_language': 'زبان منتخب کریں',
          'select_currency': 'کرنسی منتخب کریں',
          'save': 'محفوظ کریں',
          'cancel': 'منسوخ کریں',
          'delete': 'حذف کریں',
          'edit': 'ترمیم کریں',
          'search': 'تلاش کریں',
          'welcome': 'خوش آمدید',
          'transaction': 'لین دین',
          'no_data': 'کوئی ڈیٹا نہیں ملا',
          'quote1': 'ہر روپے کا حساب رکھیں۔ ہر خواب بنائیں۔',
          'quote2': 'سمجھداری سے خرچ کریں۔ مسلسل بچت کریں۔',
          'quote3': 'آج کی چھوٹی بچت، کل کی بڑی آزادی۔',
          'quote4': 'بجٹ آپ کے پیسے کو صحیح سمت دیتا ہے۔',
          'quote5': 'ہر خرچ ایک کہانی سناتا ہے۔',
          'quote6': 'پیسہ آپ کو قابو کرنے سے پہلے آپ پیسے کو قابو کریں۔',
          'quote7': 'مالی آزادی ٹریکنگ سے شروع ہوتی ہے۔',
          'quote8': 'بہتر کل کے لیے آج بچت کریں۔',
            'categories': 'اقسام',
            'new_category': 'نئی قسم',
            'add_category': 'قسم شامل کریں',
            'select_category': 'قسم منتخب کریں',
            'new_subcategory': 'نئی ذیلی قسم',
            'add_subcategory': 'ذیلی قسم شامل کریں',
            'no_categories_yet': 'ابھی تک کوئی اقسام نہیں',
            'no_subcategories': 'کوئی ذیلی اقسام نہیں',
            'category_exists': 'قسم پہلے سے موجود ہے',
            'subcategory_exists': 'ذیلی قسم پہلے سے موجود ہے',
            'category_added': 'قسم شامل کر دی گئی',
            'subcategory_added': 'ذیلی قسم شامل کر دی گئی',
            'food': 'کھانا',
            'breakfast': 'ناشتہ',
            'lunch': 'دوپہر کا کھانا',
            'dinner': 'رات کا کھانا',
            'snacks': 'ہلکی پھلکی چیزیں',

            'travel': 'سفر',
            'bus': 'بس',
            'train': 'ٹرین',
            'fuel': 'ایندھن',
            'taxi': 'ٹیکسی',

            'shopping': 'خریداری',
            'clothes': 'کپڑے',
            'electronics': 'الیکٹرانکس',
            'groceries': 'کریانہ',
            'accessories': 'لوازمات',

            'bills': 'بل',
            'electricity': 'بجلی',
            'internet': 'انٹرنیٹ',
            'water': 'پانی',
            'mobile_recharge': 'موبائل ریچارج',

            'entertainment': 'تفریح',
            'movies': 'فلمیں',
            'games': 'کھیل',
            'music': 'موسیقی',
            'ott': 'OTT',

            'health': 'صحت',
            'medicine': 'دوائی',
            'doctor': 'ڈاکٹر',
            'gym': 'جم',
            'insurance': 'انشورنس',

            'education': 'تعلیم',
            'books': 'کتابیں',
            'fees': 'فیس',
            'courses': 'کورسز',
            'stationery': 'اسٹیشنری',
            "add_transaction": "لین دین شامل کریں",
  "enter_amount": "رقم درج کریں",
  //"income": "آمدنی",
  //"expense": "خرچ",
  "select_subcategory": "ذیلی زمرہ منتخب کریں",
  "save_transaction": "محفوظ کریں",
  "reports_export": "رپورٹس اور ایکسپورٹ",
  "financial_reports": "مالی رپورٹس",
  "report_subtitle": "تاریخ کے مطابق PDF اور Excel رپورٹ بنائیں",
  "select_date_range": "تاریخ منتخب کریں",
  "choose_from_date": "ابتدائی تاریخ",
  "choose_to_date": "آخری تاریخ",
  "from": "سے",
  "to": "تک",
  "download_pdf": "PDF ڈاؤن لوڈ",
  "download_excel": "Excel ڈاؤن لوڈ",
  "upload_pdf": "PDF اپ لوڈ",
  //"analytics": "تجزیہ",
//"no_data": "کوئی ڈیٹا نہیں",
"financial_overview": "مالی جائزہ",
"category_expense": "زمرہ خرچ",
"daily_expense": "روزانہ اخراجات",
"monthly_expense": "ماہانہ اخراجات",
"salary": "تنخواہ",
"others": "دیگر",
"smart_wallet": "اسمارٹ والٹ",
//'add_transaction': 'لین دین شامل کریں',
//'save_transaction': 'لین دین محفوظ کریں',
'track_save_grow': 'ریکارڈ رکھیں • بچت کریں • ترقی کریں',
'wallet_login': 'والیٹ لاگ ان',
'username': 'صارف نام',
'password': 'پاس ورڈ',
'login': 'لاگ ان',
'register_prompt': 'اکاؤنٹ نہیں ہے؟ رجسٹر کریں',
'login_successful': 'لاگ ان کامیاب',
'invalid_credentials': 'غلط صارف نام یا پاس ورڈ',
'enter_credentials': 'براہ کرم صارف نام اور پاس ورڈ درج کریں',
'create_account': 'اکاؤنٹ بنائیں',
'fill_all_fields': 'براہ کرم تمام خانے پُر کریں',
'password_not_match': 'پاس ورڈ مطابقت نہیں رکھتے',
'account_created': 'اکاؤنٹ کامیابی سے بنا لیا گیا',
'username_exists': 'صارف نام پہلے سے موجود ہے',
'confirm_password': 'پاس ورڈ کی تصدیق کریں',
'already_have_account': 'پہلے سے اکاؤنٹ ہے؟ لاگ ان کریں',
"sub_category_expenses": "ذیلی زمرہ اخراجات",
"language": "زبان",
"manage_profiles": "پروفائل مینجمنٹ",
"manage_profiles_desc": "پروفائل تبدیل کریں، پروجیکٹ بنائیں، پروجیکٹ حذف کریں",

  "choose_profile": "پروفائل منتخب کریں",
  "choose_workspace": "اپنا ورک اسپیس منتخب کریں",
  "personal": "ذاتی",
  "manage_personal_expenses": "ذاتی اخراجات کا انتظام کریں",
  "business": "کاروبار",
  "track_business_finances": "کاروباری مالیات کا ریکارڈ رکھیں",
  "projects": "پروجیکٹس",
  "no_projects_created": "کوئی پروجیکٹ نہیں بنایا گیا",
  "create_project": "پروجیکٹ بنائیں",
  "enter_project_name": "پروجیکٹ کا نام درج کریں",
  "project_already_exists": "پروجیکٹ پہلے سے موجود ہے",
  //"cancel": "منسوخ کریں",
  "create": "بنائیں"
        },

        //////////////////////////////////////////////////
        // ODIA
        //////////////////////////////////////////////////

        'or': {
          'app_name': 'ୱାଲେଟ୍ ୱିଜ୍',
          'my_wallet': 'ମୋ ୱାଲେଟ୍',
          'income': 'ଆୟ',
          'expense': 'ଖର୍ଚ୍ଚ',
          'weekly': 'ସାପ୍ତାହିକ',
          'monthly': 'ମାସିକ',
          'yearly': 'ବାର୍ଷିକ',
          'total': 'ମୋଟ',
          'recent_transactions': 'ସମ୍ପ୍ରତିକ ଲେନଦେନ',
          'view_all': 'ସବୁ ଦେଖନ୍ତୁ',
          'home': 'ହୋମ',
          'stats': 'ପରିସଂଖ୍ୟାନ',
          'category': 'ବର୍ଗ',
          'settings': 'ସେଟିଂସ୍',
          'add': 'ଯୋଡନ୍ତୁ',
          'balance': 'ବାଲାନ୍ସ',
          'currency': 'ମୁଦ୍ରା',
          'select_language': 'ଭାଷା ବାଛନ୍ତୁ',
          'select_currency': 'ମୁଦ୍ରା ବାଛନ୍ତୁ',
          'save': 'ସେଭ୍ କରନ୍ତୁ',
          'cancel': 'ବାତିଲ୍ କରନ୍ତୁ',
          'delete': 'ଡିଲିଟ୍ କରନ୍ତୁ',
          'edit': 'ସମ୍ପାଦନ କରନ୍ତୁ',
          'search': 'ଖୋଜନ୍ତୁ',
          'welcome': 'ସ୍ୱାଗତ',
          'transaction': 'ଲେନଦେନ',
          'no_data': 'କୌଣସି ତଥ୍ୟ ମିଳିଲା ନାହିଁ',
          'quote1': 'ପ୍ରତ୍ୟେକ ଟଙ୍କାକୁ ଟ୍ରାକ୍ କରନ୍ତୁ। ପ୍ରତ୍ୟେକ ସ୍ୱପ୍ନ ଗଢନ୍ତୁ।',
          'quote2': 'ବୁଦ୍ଧିମତାର ସହ ଖର୍ଚ୍ଚ କରନ୍ତୁ। ନିୟମିତ ସଞ୍ଚୟ କରନ୍ତୁ।',
          'quote3': 'ଆଜିର ଛୋଟ ସଞ୍ଚୟ, ଆସନ୍ତାକାଲିର ବଡ ସ୍ୱାଧୀନତା।',
          'quote4': 'ବଜେଟ୍ ହେଉଛି ଆପଣଙ୍କ ଟଙ୍କା କେଉଁଠି ଯିବ ତାହା କହିବା।',
          'quote5': 'ପ୍ରତ୍ୟେକ ଖର୍ଚ୍ଚ ଗୋଟିଏ କାହାଣୀ କହେ।',
          'quote6': 'ଟଙ୍କା ଆପଣଙ୍କୁ ନିୟନ୍ତ୍ରଣ କରିବା ପୂର୍ବରୁ ଆପଣ ଟଙ୍କାକୁ ନିୟନ୍ତ୍ରଣ କରନ୍ତୁ।',
          'quote7': 'ଆର୍ଥିକ ସ୍ୱାଧୀନତା ଟ୍ରାକିଂରୁ ଆରମ୍ଭ ହୁଏ।',
          'quote8': 'ଭଲ ଆସନ୍ତାକାଲି ପାଇଁ ଆଜି ସଞ୍ଚୟ କରନ୍ତୁ।',
          'categories': 'ଶ୍ରେଣୀଗୁଡ଼ିକ',
          'new_category': 'ନୂତନ ଶ୍ରେଣୀ',
          'add_category': 'ଶ୍ରେଣୀ ଯୋଡନ୍ତୁ',
          'select_category': 'ଶ୍ରେଣୀ ବାଛନ୍ତୁ',
          'new_subcategory': 'ନୂତନ ଉପଶ୍ରେଣୀ',
          'add_subcategory': 'ଉପଶ୍ରେଣୀ ଯୋଡନ୍ତୁ',
          'no_categories_yet': 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଶ୍ରେଣୀ ନାହିଁ',
          'no_subcategories': 'କୌଣସି ଉପଶ୍ରେଣୀ ନାହିଁ',
          'category_exists': 'ଶ୍ରେଣୀ ପୂର୍ବରୁ ଅଛି',
          'subcategory_exists': 'ଉପଶ୍ରେଣୀ ପୂର୍ବରୁ ଅଛି',
          'category_added': 'ଶ୍ରେଣୀ ଯୋଡାଗଲା',
          'subcategory_added': 'ଉପଶ୍ରେଣୀ ଯୋଡାଗଲା',
            'food': 'ଖାଦ୍ୟ',
            'breakfast': 'ସକାଳ ଖାଦ୍ୟ',
            'lunch': 'ମଧ୍ୟାହ୍ନ ଭୋଜନ',
            'dinner': 'ରାତି ଭୋଜନ',
            'snacks': 'ହାଲୁକା ଖାଦ୍ୟ',

            'travel': 'ଭ୍ରମଣ',
            'bus': 'ବସ',
            'train': 'ଟ୍ରେନ',
            'fuel': 'ଇନ୍ଧନ',
            'taxi': 'ଟାକ୍ସି',

            'shopping': 'କିଣାକାଟା',
            'clothes': 'ବସ୍ତ୍ର',
            'electronics': 'ଇଲେକ୍ଟ୍ରୋନିକ୍ସ',
            'groceries': 'କିରାଣା',
            'accessories': 'ଏକ୍ସେସରୀଜ୍',

            'bills': 'ବିଲ୍',
            'electricity': 'ବିଦ୍ୟୁତ',
            'internet': 'ଇଣ୍ଟରନେଟ',
            'water': 'ପାଣି',
            'mobile_recharge': 'ମୋବାଇଲ ରିଚାର୍ଜ',

            'entertainment': 'ମନୋରଞ୍ଜନ',
            'movies': 'ସିନେମା',
            'games': 'ଖେଳ',
            'music': 'ସଙ୍ଗୀତ',
            'ott': 'OTT',

            'health': 'ସ୍ୱାସ୍ଥ୍ୟ',
            'medicine': 'ଔଷଧ',
            'doctor': 'ଡାକ୍ତର',
            'gym': 'ଜିମ୍',
            'insurance': 'ବୀମା',

            'education': 'ଶିକ୍ଷା',
            'books': 'ପୁସ୍ତକ',
            'fees': 'ଶୁଳ୍କ',
            'courses': 'ପାଠ୍ୟକ୍ରମ',
            'stationery': 'ଷ୍ଟେସନେରୀ',
             "add_transaction": "ଲେନଦେନ ଯୋଡନ୍ତୁ",
  "enter_amount": "ରାଶି ଦିଅନ୍ତୁ",
 // "income": "ଆୟ",
  //"expense": "ଖର୍ଚ୍ଚ",
  "select_subcategory": "ଉପଶ୍ରେଣୀ ବାଛନ୍ତୁ",
  "save_transaction": "ସେଭ୍ କରନ୍ତୁ",
  "reports_export": "ରିପୋର୍ଟ ଏବଂ ଏକ୍ସପୋର୍ଟ",
  "financial_reports": "ଆର୍ଥିକ ରିପୋର୍ଟ",
  "report_subtitle": "ତାରିଖ ଅନୁସାରେ PDF ଏବଂ Excel ରିପୋର୍ଟ ତିଆରି କରନ୍ତୁ",
  "select_date_range": "ତାରିଖ ଚୟନ କରନ୍ତୁ",
  "choose_from_date": "ଆରମ୍ଭ ତାରିଖ",
  "choose_to_date": "ଶେଷ ତାରିଖ",
  "from": "ରୁ",
  "to": "ପର୍ଯ୍ୟନ୍ତ",
  "download_pdf": "PDF ଡାଉନଲୋଡ୍",
  "download_excel": "Excel ଡାଉନଲୋଡ୍",
  "upload_pdf": "PDF ଅପଲୋଡ୍",

   // "analytics": "ବିଶ୍ଳେଷଣ",
//"no_data": "କୌଣସି ତଥ୍ୟ ନାହିଁ",
"financial_overview": "ଆର୍ଥିକ ସାରାଂଶ",
"category_expense": "ଶ୍ରେଣୀ ଖର୍ଚ୍ଚ",
"daily_expense": "ଦୈନିକ ଖର୍ଚ୍ଚ",
"monthly_expense": "ମାସିକ ଖର୍ଚ୍ଚ",
"salary": "ବେତନ",
"others": "ଅନ୍ୟ",
"smart_wallet": "ସ୍ମାର୍ଟ ୱାଲେଟ",
//'add_transaction': 'ଲେନଦେନ ଯୋଡନ୍ତୁ',
//'save_transaction': 'ଲେନଦେନ ସଂରକ୍ଷଣ କରନ୍ତୁ',
'track_save_grow': 'ଟ୍ରାକ୍ କରନ୍ତୁ • ସଞ୍ଚୟ କରନ୍ତୁ • ଉନ୍ନତି କରନ୍ତୁ',
'wallet_login': 'ୱାଲେଟ ଲଗଇନ୍',
'username': 'ବ୍ୟବହାରକାରୀ ନାମ',
'password': 'ପାସୱାର୍ଡ',
'login': 'ଲଗଇନ୍',
'register_prompt': 'ଖାତା ନାହିଁ କି? ପଞ୍ଜିକରଣ କରନ୍ତୁ',
'login_successful': 'ଲଗଇନ୍ ସଫଳ',
'invalid_credentials': 'ଭୁଲ ବ୍ୟବହାରକାରୀ ନାମ କିମ୍ବା ପାସୱାର୍ଡ',
'enter_credentials': 'ଦୟାକରି ବ୍ୟବହାରକାରୀ ନାମ ଏବଂ ପାସୱାର୍ଡ ଦିଅନ୍ତୁ',

'create_account': 'ଖାତା ସୃଷ୍ଟି କରନ୍ତୁ',
'fill_all_fields': 'ଦୟାକରି ସମସ୍ତ ଘର ପୂରଣ କରନ୍ତୁ',
'password_not_match': 'ପାସୱାର୍ଡ ମେଳ ଖାଉନାହିଁ',
'account_created': 'ଖାତା ସଫଳତାର ସହିତ ସୃଷ୍ଟି ହୋଇଛି',
'username_exists': 'ଉପଯୋଗକର୍ତ୍ତା ନାମ ପୂର୍ବରୁ ଅଛି',
'confirm_password': 'ପାସୱାର୍ଡ ନିଶ୍ଚିତ କରନ୍ତୁ',
'already_have_account': 'ପୂର୍ବରୁ ଖାତା ଅଛି କି? ଲଗଇନ କରନ୍ତୁ',
"sub_category_expenses": "ଉପ-ଶ୍ରେଣୀ ଖର୍ଚ୍ଚ",
"language": "ଭାଷା",
"manage_profiles": "ପ୍ରୋଫାଇଲ୍ ପରିଚାଳନା",
"manage_profiles_desc": "ପ୍ରୋଫାଇଲ୍ ବଦଳାନ୍ତୁ, ପ୍ରୋଜେକ୍ଟ ସୃଷ୍ଟି କରନ୍ତୁ, ପ୍ରୋଜେକ୍ଟ ବିଲୋପ କରନ୍ତୁ",
  "choose_profile": "ପ୍ରୋଫାଇଲ୍ ବାଛନ୍ତୁ",
  "choose_workspace": "ଆପଣଙ୍କର କାର୍ଯ୍ୟକ୍ଷେତ୍ର ବାଛନ୍ତୁ",
  "personal": "ବ୍ୟକ୍ତିଗତ",
  "manage_personal_expenses": "ବ୍ୟକ୍ତିଗତ ଖର୍ଚ୍ଚ ପରିଚାଳନା କରନ୍ତୁ",
  "business": "ବ୍ୟବସାୟ",
  "track_business_finances": "ବ୍ୟବସାୟିକ ଆର୍ଥିକତାକୁ ଟ୍ରାକ୍ କରନ୍ତୁ",
  "projects": "ପ୍ରକଳ୍ପଗୁଡ଼ିକ",
  "no_projects_created": "କୌଣସି ପ୍ରକଳ୍ପ ସୃଷ୍ଟି ହୋଇନାହିଁ",
  "create_project": "ପ୍ରକଳ୍ପ ସୃଷ୍ଟି କରନ୍ତୁ",
  "enter_project_name": "ପ୍ରକଳ୍ପର ନାମ ପ୍ରବେଶ କରନ୍ତୁ",
  "project_already_exists": "ପ୍ରକଳ୍ପ ପୂର୍ବରୁ ଅବସ୍ଥିତ",
  //"cancel": "ବାତିଲ୍",
  "create": "ସୃଷ୍ଟି କରନ୍ତୁ"

        },
      };
  //////////////////////////////////////////////////
  // TRANSLATE
  //////////////////////////////////////////////////
  String translate(String key) {
    return localizedValues[locale.languageCode]
            ?[key] ??
        localizedValues['en']?[key] ??
        key;
  }

  //////////////////////////////////////////////////
  // SHORTCUT
  //////////////////////////////////////////////////
  String tr(String key) {
    return translate(key);
  }
}
//////////////////////////////////////////////////
// LOCALIZATION DELEGATE
//////////////////////////////////////////////////

class AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {

  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return const [
      'en',
      'ta',
      'hi',
      'te',
      'ml',
      'kn',
      'bn',
      'gu',
      'mr',
      'pa',
      'ur',
      'or',
    ].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(
    covariant LocalizationsDelegate<AppLocalizations> old,
  ) {
    return false; 
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other);

  @override
  int get hashCode => runtimeType.hashCode;

  @override
  Type get type => AppLocalizations;
}